// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ApiKeyControllerCreateApiKeyData,
  ApiKeyControllerCreateApiKeyResponses,
  ApiKeyControllerListApiKeysData,
  ApiKeyControllerListApiKeysResponses,
  ApiKeyControllerRevokeApiKeyData,
  ApiKeyControllerRevokeApiKeyResponses,
  AppControllerGetHelloData,
  AppControllerGetHelloResponses,
  AppsControllerCreateAppData,
  AppsControllerCreateAppResponses,
  AppsControllerDeleteAppData,
  AppsControllerDeleteAppResponses,
  AppsControllerEditAppData,
  AppsControllerEditAppResponses,
  AppsControllerGetAllAppsData,
  AppsControllerGetAllAppsResponses,
  AppsControllerGetAppData,
  AppsControllerGetAppResponses,
  AuditLogControllerListAuditLogsData,
  AuditLogControllerListAuditLogsResponses,
  AuthControllerGoogleAuthData,
  AuthControllerGoogleAuthResponses,
  AuthControllerRefreshData,
  AuthControllerRefreshResponses,
  AuthControllerSetupOrgData,
  AuthControllerSetupOrgResponses,
  AuthControllerSignInData,
  AuthControllerSignInResponses,
  AuthControllerSignUpData,
  AuthControllerSignUpResponses,
  ChannelControllerCreateChannelData,
  ChannelControllerCreateChannelResponses,
  ChannelControllerDeleteChannelData,
  ChannelControllerDeleteChannelResponses,
  ChannelControllerGetChannelData,
  ChannelControllerGetChannelResponses,
  ChannelControllerUpdateChannelData,
  ChannelControllerUpdateChannelResponses,
  EnvironmentControllerCreateData,
  EnvironmentControllerCreateResponses,
  EnvironmentControllerListData,
  EnvironmentControllerListResponses,
  EnvironmentControllerPromoteData,
  EnvironmentControllerPromoteResponses,
  EnvironmentControllerRemoveData,
  EnvironmentControllerRemoveResponses,
  EnvironmentControllerUpdateData,
  EnvironmentControllerUpdateResponses,
  EventControllerCreateEventData,
  EventControllerCreateEventResponses,
  EventControllerListEventsData,
  EventControllerListEventsResponses,
  EventsSearchControllerSearchData,
  EventsSearchControllerSearchResponses,
  FeatureFlagsControllerMeData,
  FeatureFlagsControllerMeResponses,
  HealthControllerCheckData,
  HealthControllerCheckResponses,
  IotCredentialsControllerGetCredentialsData,
  IotCredentialsControllerGetCredentialsResponses,
  OrganizationControllerCreateInvitationData,
  OrganizationControllerCreateInvitationResponses,
  OrganizationControllerCreateOrganizationData,
  OrganizationControllerCreateOrganizationResponses,
  OrganizationControllerDeleteInvitationData,
  OrganizationControllerDeleteInvitationResponses,
  OrganizationControllerDeleteOrganizationData,
  OrganizationControllerDeleteOrganizationResponses,
  OrganizationControllerEditOrganizationData,
  OrganizationControllerEditOrganizationResponses,
  OrganizationControllerGetAllOrganizationsData,
  OrganizationControllerGetAllOrganizationsResponses,
  OrganizationControllerGetOrganizationData,
  OrganizationControllerGetOrganizationResponses,
  OrganizationControllerRemoveMemberData,
  OrganizationControllerRemoveMemberResponses,
  OrganizationControllerTransferOwnershipData,
  OrganizationControllerTransferOwnershipResponses,
  OtlpControllerIngestLogsData,
  OtlpControllerIngestLogsResponses,
  OtlpControllerIngestTracesData,
  OtlpControllerIngestTracesResponses,
  PublicIngestTokenControllerCreateData,
  PublicIngestTokenControllerCreateResponses,
  PublicIngestTokenControllerListData,
  PublicIngestTokenControllerListResponses,
  PublicIngestTokenControllerRevokeData,
  PublicIngestTokenControllerRevokeResponses,
  ReleaseControllerCreateData,
  ReleaseControllerCreateResponses,
  ReleaseControllerListData,
  ReleaseControllerListResponses,
  ReleaseControllerUploadArtifactData,
  ReleaseControllerUploadArtifactResponses,
  SentryControllerIngestEnvelopeData,
  SentryControllerIngestEnvelopeResponses,
  SentryControllerIngestMinidumpData,
  SentryControllerIngestMinidumpResponses,
  SentryControllerIngestSecurityData,
  SentryControllerIngestSecurityResponses,
  SentryControllerIngestStoreData,
  SentryControllerIngestStoreResponses,
  SsoControllerAuthorizeData,
  SsoControllerAuthorizeResponses,
  SsoControllerCallbackData,
  SsoControllerCallbackResponses,
  SsoControllerCreateConnectionData,
  SsoControllerCreateConnectionResponses,
  SsoControllerDeleteConnectionData,
  SsoControllerDeleteConnectionResponses,
  SsoControllerGetConnectionsData,
  SsoControllerGetConnectionsResponses,
  SsoControllerSamlAcsData,
  SsoControllerSamlAcsResponses,
  SsoControllerToggleEnforcementData,
  SsoControllerToggleEnforcementResponses,
  TraceControllerGetDashboardStatsData,
  TraceControllerGetDashboardStatsResponses,
  TraceControllerGetTraceEventsData,
  TraceControllerGetTraceEventsResponses,
  TraceControllerGetTraceSummaryData,
  TraceControllerGetTraceSummaryResponses,
  TraceControllerListTracesData,
  TraceControllerListTracesResponses,
  UserControllerDeleteUserData,
  UserControllerDeleteUserResponses,
  UserControllerGetMeData,
  UserControllerGetMeResponses,
  UserControllerGetMyOrganizationsData,
  UserControllerGetMyOrganizationsResponses,
  UserControllerGetUsersData,
  UserControllerGetUsersResponses,
  UserControllerSwitchActiveOrgData,
  UserControllerSwitchActiveOrgResponses,
  UserControllerUpdateMeData,
  UserControllerUpdateMeResponses,
  UserControllerUpdateUserData,
  UserControllerUpdateUserResponses,
  WebhookControllerCreateEndpointData,
  WebhookControllerCreateEndpointResponses,
  WebhookControllerDeleteEndpointData,
  WebhookControllerDeleteEndpointResponses,
  WebhookControllerGetDeliveriesData,
  WebhookControllerGetDeliveriesResponses,
  WebhookControllerIngestWebhookData,
  WebhookControllerIngestWebhookResponses,
  WebhookControllerListEndpointsData,
  WebhookControllerListEndpointsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerGetHelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });

export const authControllerSignUp = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSignUpData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerSignUpResponses, unknown, ThrowOnError>({
    url: "/auth/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const authControllerSignIn = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSignInData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerSignInResponses, unknown, ThrowOnError>({
    url: "/auth/signin",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const authControllerGoogleAuth = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerGoogleAuthData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerGoogleAuthResponses, unknown, ThrowOnError>({
    url: "/auth/google",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const authControllerSetupOrg = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerSetupOrgData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerSetupOrgResponses, unknown, ThrowOnError>({
    url: "/auth/setup-org",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const authControllerRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRefreshData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthControllerRefreshResponses, unknown, ThrowOnError>({
    url: "/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const iotCredentialsControllerGetCredentials = <ThrowOnError extends boolean = false>(
  options?: Options<IotCredentialsControllerGetCredentialsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    IotCredentialsControllerGetCredentialsResponses,
    unknown,
    ThrowOnError
  >({ url: "/auth/iot-credentials", ...options });

export const userControllerGetMe = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UserControllerGetMeResponses, unknown, ThrowOnError>({
    url: "/users/me",
    ...options,
  });

export const userControllerUpdateMe = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateMeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserControllerUpdateMeResponses, unknown, ThrowOnError>({
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const userControllerGetMyOrganizations = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetMyOrganizationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UserControllerGetMyOrganizationsResponses, unknown, ThrowOnError>(
    { url: "/users/me/organizations", ...options },
  );

export const userControllerSwitchActiveOrg = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerSwitchActiveOrgData, ThrowOnError>,
) =>
  (options.client ?? client).patch<UserControllerSwitchActiveOrgResponses, unknown, ThrowOnError>({
    url: "/users/me/active-org",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const userControllerGetUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UserControllerGetUsersResponses, unknown, ThrowOnError>({
    url: "/users",
    ...options,
  });

export const userControllerDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UserControllerDeleteUserResponses, unknown, ThrowOnError>({
    url: "/users/{id}",
    ...options,
  });

export const userControllerUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerUpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).put<UserControllerUpdateUserResponses, unknown, ThrowOnError>({
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const organizationControllerGetAllOrganizations = <ThrowOnError extends boolean = false>(
  options?: Options<OrganizationControllerGetAllOrganizationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    OrganizationControllerGetAllOrganizationsResponses,
    unknown,
    ThrowOnError
  >({ url: "/organizations", ...options });

export const organizationControllerCreateOrganization = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerCreateOrganizationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OrganizationControllerCreateOrganizationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/organizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const organizationControllerDeleteOrganization = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerDeleteOrganizationData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    OrganizationControllerDeleteOrganizationResponses,
    unknown,
    ThrowOnError
  >({ url: "/organizations/{id}", ...options });

export const organizationControllerGetOrganization = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerGetOrganizationData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    OrganizationControllerGetOrganizationResponses,
    unknown,
    ThrowOnError
  >({ url: "/organizations/{id}", ...options });

export const organizationControllerEditOrganization = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerEditOrganizationData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    OrganizationControllerEditOrganizationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/organizations/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const organizationControllerCreateInvitation = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerCreateInvitationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OrganizationControllerCreateInvitationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/organizations/{id}/invitations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const organizationControllerRemoveMember = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerRemoveMemberData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    OrganizationControllerRemoveMemberResponses,
    unknown,
    ThrowOnError
  >({ url: "/organizations/{id}/members/{userId}", ...options });

export const organizationControllerTransferOwnership = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerTransferOwnershipData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    OrganizationControllerTransferOwnershipResponses,
    unknown,
    ThrowOnError
  >({
    url: "/organizations/{id}/transfer-ownership",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const organizationControllerDeleteInvitation = <ThrowOnError extends boolean = false>(
  options: Options<OrganizationControllerDeleteInvitationData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    OrganizationControllerDeleteInvitationResponses,
    unknown,
    ThrowOnError
  >({ url: "/organizations/{id}/invitations/{invitationId}", ...options });

export const featureFlagsControllerMe = <ThrowOnError extends boolean = false>(
  options?: Options<FeatureFlagsControllerMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<FeatureFlagsControllerMeResponses, unknown, ThrowOnError>({
    url: "/feature-flags/me",
    ...options,
  });

export const environmentControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<EnvironmentControllerListData, ThrowOnError>,
) =>
  (options?.client ?? client).get<EnvironmentControllerListResponses, unknown, ThrowOnError>({
    url: "/environments",
    ...options,
  });

export const environmentControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<EnvironmentControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<EnvironmentControllerCreateResponses, unknown, ThrowOnError>({
    url: "/environments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const environmentControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<EnvironmentControllerRemoveData, ThrowOnError>,
) =>
  (options.client ?? client).delete<EnvironmentControllerRemoveResponses, unknown, ThrowOnError>({
    url: "/environments/{id}",
    ...options,
  });

export const environmentControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<EnvironmentControllerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<EnvironmentControllerUpdateResponses, unknown, ThrowOnError>({
    url: "/environments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const environmentControllerPromote = <ThrowOnError extends boolean = false>(
  options: Options<EnvironmentControllerPromoteData, ThrowOnError>,
) =>
  (options.client ?? client).post<EnvironmentControllerPromoteResponses, unknown, ThrowOnError>({
    url: "/environments/{id}/promote-to-default",
    ...options,
  });

export const apiKeyControllerListApiKeys = <ThrowOnError extends boolean = false>(
  options?: Options<ApiKeyControllerListApiKeysData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ApiKeyControllerListApiKeysResponses, unknown, ThrowOnError>({
    url: "/api-keys",
    ...options,
  });

export const apiKeyControllerCreateApiKey = <ThrowOnError extends boolean = false>(
  options: Options<ApiKeyControllerCreateApiKeyData, ThrowOnError>,
) =>
  (options.client ?? client).post<ApiKeyControllerCreateApiKeyResponses, unknown, ThrowOnError>({
    url: "/api-keys",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const apiKeyControllerRevokeApiKey = <ThrowOnError extends boolean = false>(
  options: Options<ApiKeyControllerRevokeApiKeyData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ApiKeyControllerRevokeApiKeyResponses, unknown, ThrowOnError>({
    url: "/api-keys/{id}",
    ...options,
  });

export const publicIngestTokenControllerList = <ThrowOnError extends boolean = false>(
  options?: Options<PublicIngestTokenControllerListData, ThrowOnError>,
) =>
  (options?.client ?? client).get<PublicIngestTokenControllerListResponses, unknown, ThrowOnError>({
    url: "/public-tokens",
    ...options,
  });

export const publicIngestTokenControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<PublicIngestTokenControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PublicIngestTokenControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/public-tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const publicIngestTokenControllerRevoke = <ThrowOnError extends boolean = false>(
  options: Options<PublicIngestTokenControllerRevokeData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    PublicIngestTokenControllerRevokeResponses,
    unknown,
    ThrowOnError
  >({ url: "/public-tokens/{id}", ...options });

export const channelControllerDeleteChannel = <ThrowOnError extends boolean = false>(
  options: Options<ChannelControllerDeleteChannelData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ChannelControllerDeleteChannelResponses, unknown, ThrowOnError>(
    { url: "/channel/{id}", ...options },
  );

export const channelControllerGetChannel = <ThrowOnError extends boolean = false>(
  options: Options<ChannelControllerGetChannelData, ThrowOnError>,
) =>
  (options.client ?? client).get<ChannelControllerGetChannelResponses, unknown, ThrowOnError>({
    url: "/channel/{id}",
    ...options,
  });

export const channelControllerUpdateChannel = <ThrowOnError extends boolean = false>(
  options: Options<ChannelControllerUpdateChannelData, ThrowOnError>,
) =>
  (options.client ?? client).put<ChannelControllerUpdateChannelResponses, unknown, ThrowOnError>({
    url: "/channel/{id}",
    ...options,
  });

export const channelControllerCreateChannel = <ThrowOnError extends boolean = false>(
  options: Options<ChannelControllerCreateChannelData, ThrowOnError>,
) =>
  (options.client ?? client).post<ChannelControllerCreateChannelResponses, unknown, ThrowOnError>({
    url: "/channel",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const eventControllerCreateEvent = <ThrowOnError extends boolean = false>(
  options: Options<EventControllerCreateEventData, ThrowOnError>,
) =>
  (options.client ?? client).post<EventControllerCreateEventResponses, unknown, ThrowOnError>({
    url: "/event",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const eventControllerListEvents = <ThrowOnError extends boolean = false>(
  options: Options<EventControllerListEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<EventControllerListEventsResponses, unknown, ThrowOnError>({
    url: "/event/{channelId}/list",
    ...options,
  });

export const eventsSearchControllerSearch = <ThrowOnError extends boolean = false>(
  options?: Options<EventsSearchControllerSearchData, ThrowOnError>,
) =>
  (options?.client ?? client).get<EventsSearchControllerSearchResponses, unknown, ThrowOnError>({
    url: "/events/search",
    ...options,
  });

export const appsControllerGetAllApps = <ThrowOnError extends boolean = false>(
  options?: Options<AppsControllerGetAllAppsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AppsControllerGetAllAppsResponses, unknown, ThrowOnError>({
    url: "/apps",
    ...options,
  });

export const appsControllerCreateApp = <ThrowOnError extends boolean = false>(
  options: Options<AppsControllerCreateAppData, ThrowOnError>,
) =>
  (options.client ?? client).post<AppsControllerCreateAppResponses, unknown, ThrowOnError>({
    url: "/apps",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsControllerDeleteApp = <ThrowOnError extends boolean = false>(
  options: Options<AppsControllerDeleteAppData, ThrowOnError>,
) =>
  (options.client ?? client).delete<AppsControllerDeleteAppResponses, unknown, ThrowOnError>({
    url: "/apps/{id}",
    ...options,
  });

export const appsControllerGetApp = <ThrowOnError extends boolean = false>(
  options: Options<AppsControllerGetAppData, ThrowOnError>,
) =>
  (options.client ?? client).get<AppsControllerGetAppResponses, unknown, ThrowOnError>({
    url: "/apps/{id}",
    ...options,
  });

export const appsControllerEditApp = <ThrowOnError extends boolean = false>(
  options: Options<AppsControllerEditAppData, ThrowOnError>,
) =>
  (options.client ?? client).patch<AppsControllerEditAppResponses, unknown, ThrowOnError>({
    url: "/apps/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const webhookControllerCreateEndpoint = <ThrowOnError extends boolean = false>(
  options: Options<WebhookControllerCreateEndpointData, ThrowOnError>,
) =>
  (options.client ?? client).post<WebhookControllerCreateEndpointResponses, unknown, ThrowOnError>({
    url: "/webhooks/endpoints",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const webhookControllerListEndpoints = <ThrowOnError extends boolean = false>(
  options: Options<WebhookControllerListEndpointsData, ThrowOnError>,
) =>
  (options.client ?? client).get<WebhookControllerListEndpointsResponses, unknown, ThrowOnError>({
    url: "/webhooks/endpoints/channel/{channelId}",
    ...options,
  });

export const webhookControllerDeleteEndpoint = <ThrowOnError extends boolean = false>(
  options: Options<WebhookControllerDeleteEndpointData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    WebhookControllerDeleteEndpointResponses,
    unknown,
    ThrowOnError
  >({ url: "/webhooks/endpoints/{id}", ...options });

export const webhookControllerGetDeliveries = <ThrowOnError extends boolean = false>(
  options: Options<WebhookControllerGetDeliveriesData, ThrowOnError>,
) =>
  (options.client ?? client).get<WebhookControllerGetDeliveriesResponses, unknown, ThrowOnError>({
    url: "/webhooks/deliveries/{endpointId}",
    ...options,
  });

export const webhookControllerIngestWebhook = <ThrowOnError extends boolean = false>(
  options: Options<WebhookControllerIngestWebhookData, ThrowOnError>,
) =>
  (options.client ?? client).post<WebhookControllerIngestWebhookResponses, unknown, ThrowOnError>({
    url: "/webhooks/ingest/{endpointId}",
    ...options,
  });

export const traceControllerListTraces = <ThrowOnError extends boolean = false>(
  options?: Options<TraceControllerListTracesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TraceControllerListTracesResponses, unknown, ThrowOnError>({
    url: "/traces",
    ...options,
  });

export const traceControllerGetDashboardStats = <ThrowOnError extends boolean = false>(
  options?: Options<TraceControllerGetDashboardStatsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<TraceControllerGetDashboardStatsResponses, unknown, ThrowOnError>(
    { url: "/traces/stats", ...options },
  );

export const traceControllerGetTraceEvents = <ThrowOnError extends boolean = false>(
  options: Options<TraceControllerGetTraceEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<TraceControllerGetTraceEventsResponses, unknown, ThrowOnError>({
    url: "/traces/{traceId}/events",
    ...options,
  });

export const traceControllerGetTraceSummary = <ThrowOnError extends boolean = false>(
  options: Options<TraceControllerGetTraceSummaryData, ThrowOnError>,
) =>
  (options.client ?? client).get<TraceControllerGetTraceSummaryResponses, unknown, ThrowOnError>({
    url: "/traces/{traceId}/summary",
    ...options,
  });

export const auditLogControllerListAuditLogs = <ThrowOnError extends boolean = false>(
  options?: Options<AuditLogControllerListAuditLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuditLogControllerListAuditLogsResponses, unknown, ThrowOnError>({
    url: "/audit-logs",
    ...options,
  });

/**
 * OTLP/HTTP logs ingest (protobuf or JSON)
 */
export const otlpControllerIngestLogs = <ThrowOnError extends boolean = false>(
  options: Options<OtlpControllerIngestLogsData, ThrowOnError>,
) =>
  (options.client ?? client).post<OtlpControllerIngestLogsResponses, unknown, ThrowOnError>({
    url: "/v1/logs",
    ...options,
  });

/**
 * OTLP/HTTP traces ingest (protobuf or JSON)
 */
export const otlpControllerIngestTraces = <ThrowOnError extends boolean = false>(
  options: Options<OtlpControllerIngestTracesData, ThrowOnError>,
) =>
  (options.client ?? client).post<OtlpControllerIngestTracesResponses, unknown, ThrowOnError>({
    url: "/v1/traces",
    ...options,
  });

export const healthControllerCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthControllerCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HealthControllerCheckResponses, unknown, ThrowOnError>({
    url: "/health",
    ...options,
  });

export const releaseControllerList = <ThrowOnError extends boolean = false>(
  options: Options<ReleaseControllerListData, ThrowOnError>,
) =>
  (options.client ?? client).get<ReleaseControllerListResponses, unknown, ThrowOnError>({
    url: "/organizations/{orgId}/releases",
    ...options,
  });

export const releaseControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ReleaseControllerCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReleaseControllerCreateResponses, unknown, ThrowOnError>({
    url: "/organizations/{orgId}/releases",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const releaseControllerUploadArtifact = <ThrowOnError extends boolean = false>(
  options: Options<ReleaseControllerUploadArtifactData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReleaseControllerUploadArtifactResponses, unknown, ThrowOnError>({
    url: "/releases/{version}/artifacts",
    ...options,
  });

/**
 * Sentry-compatible envelope ingest
 */
export const sentryControllerIngestEnvelope = <ThrowOnError extends boolean = false>(
  options: Options<SentryControllerIngestEnvelopeData, ThrowOnError>,
) =>
  (options.client ?? client).post<SentryControllerIngestEnvelopeResponses, unknown, ThrowOnError>({
    url: "/api/{projectId}/envelope",
    ...options,
  });

export const sentryControllerIngestStore = <ThrowOnError extends boolean = false>(
  options: Options<SentryControllerIngestStoreData, ThrowOnError>,
) =>
  (options.client ?? client).post<SentryControllerIngestStoreResponses, unknown, ThrowOnError>({
    url: "/api/{projectId}/store",
    ...options,
  });

export const sentryControllerIngestSecurity = <ThrowOnError extends boolean = false>(
  options: Options<SentryControllerIngestSecurityData, ThrowOnError>,
) =>
  (options.client ?? client).post<SentryControllerIngestSecurityResponses, unknown, ThrowOnError>({
    url: "/api/{projectId}/security",
    ...options,
  });

export const sentryControllerIngestMinidump = <ThrowOnError extends boolean = false>(
  options: Options<SentryControllerIngestMinidumpData, ThrowOnError>,
) =>
  (options.client ?? client).post<SentryControllerIngestMinidumpResponses, unknown, ThrowOnError>({
    url: "/api/{projectId}/minidump",
    ...options,
  });

export const ssoControllerGetConnections = <ThrowOnError extends boolean = false>(
  options?: Options<SsoControllerGetConnectionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SsoControllerGetConnectionsResponses, unknown, ThrowOnError>({
    url: "/sso/connections",
    ...options,
  });

export const ssoControllerCreateConnection = <ThrowOnError extends boolean = false>(
  options?: Options<SsoControllerCreateConnectionData, ThrowOnError>,
) =>
  (options?.client ?? client).post<SsoControllerCreateConnectionResponses, unknown, ThrowOnError>({
    url: "/sso/connections",
    ...options,
  });

export const ssoControllerDeleteConnection = <ThrowOnError extends boolean = false>(
  options: Options<SsoControllerDeleteConnectionData, ThrowOnError>,
) =>
  (options.client ?? client).delete<SsoControllerDeleteConnectionResponses, unknown, ThrowOnError>({
    url: "/sso/connections/{clientID}",
    ...options,
  });

export const ssoControllerToggleEnforcement = <ThrowOnError extends boolean = false>(
  options: Options<SsoControllerToggleEnforcementData, ThrowOnError>,
) =>
  (options.client ?? client).patch<SsoControllerToggleEnforcementResponses, unknown, ThrowOnError>({
    url: "/sso/enforcement",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ssoControllerAuthorize = <ThrowOnError extends boolean = false>(
  options?: Options<SsoControllerAuthorizeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<SsoControllerAuthorizeResponses, unknown, ThrowOnError>({
    url: "/auth/sso/authorize",
    ...options,
  });

export const ssoControllerCallback = <ThrowOnError extends boolean = false>(
  options: Options<SsoControllerCallbackData, ThrowOnError>,
) =>
  (options.client ?? client).post<SsoControllerCallbackResponses, unknown, ThrowOnError>({
    url: "/auth/sso/callback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const ssoControllerSamlAcs = <ThrowOnError extends boolean = false>(
  options?: Options<SsoControllerSamlAcsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<SsoControllerSamlAcsResponses, unknown, ThrowOnError>({
    url: "/auth/sso/acs",
    ...options,
  });
