// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type Function = {
    [key: string]: unknown;
};

export type UserCreateDto = {
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    password: string;
    action: 'create' | 'join';
    orgCreateProps?: Function;
    invitationCode?: string;
};

export type UserResponseDto = {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
    username: string;
    googleId: string | null;
    roles: Array<'user' | 'admin' | 'owner'>;
    organizationId: string | null;
    /**
     * Whether this account has product-wide superadmin (admin panel) access
     */
    isSuperAdmin: boolean;
    deletedAt?: string | null;
};

export type SignInDto = {
    email: string;
    password: string;
};

export type AuthTokensResponseDto = {
    access_token: string;
    refresh_token: string;
};

export type GoogleAuthDto = {
    code?: string;
    idToken?: string;
};

export type GoogleAuthResponseDto = {
    access_token: string;
    refresh_token: string;
    needsOrg?: boolean;
};

export type CreateOrganizationDto = {
    name: string;
    slug: string;
    description?: string;
};

export type SetupOrgDto = {
    action: 'create' | 'join';
    orgCreateProps?: CreateOrganizationDto;
    invitationCode?: string;
};

export type RefreshTokenDto = {
    refresh_token: string;
};

export type IotCredentialsResponseDto = {
    endpoint: string;
    presignedWssUrl: string;
    expiresAt: string;
    /**
     * Org-scoped MQTT topic prefix. Subscribe topics must extend this with `/{envSlug}/{appId}/{channelId}/{eventType}/{agentId}` (use `+` for wildcards).
     */
    topicPrefix: string;
    /**
     * Default environment slug for this org. Frontends should slot this segment between `topicPrefix` and the appId when subscribing without an explicit env.
     */
    envSlug: string;
    /**
     * Human-readable template showing every topic segment the broker will publish to. Mirrors the publish-side topic-builder layout.
     */
    topicTemplate: string;
    clientId: string;
    region: string;
    /**
     * IoT custom authorizer name to invoke. Already encoded in `presignedWssUrl` query string; exposed for clients that need to set it via header.
     */
    authorizerName?: string;
    /**
     * Bearer token to pass as the MQTT CONNECT username. The IoT custom authorizer reads it from `mqttContext.username`.
     */
    authToken?: string;
};

export type UpdateProfileDto = {
    first_name?: string;
    last_name?: string;
};

export type InvitationResponseDto = {
    id: string;
    invitationId: string;
    orgId: string;
    invitedEmail: string;
    role: string;
    inviteRole?: string;
    code?: string;
    status: string;
    expiresAt?: string;
    acceptedAt?: string;
    createdAt: string;
    updatedAt?: string;
};

export type EnvironmentResponseDto = {
    id: string;
    environmentId: string;
    orgId: string;
    name: string;
    slug: string;
    color?: string;
    isDefault?: boolean;
    isProduction?: boolean;
    isEphemeral?: boolean;
    expiresAt?: string;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
};

export type OrganizationResponseDto = {
    id: string;
    orgId: string;
    name: string;
    slug: string;
    description?: string;
    plan: string;
    ssoEnforced: boolean;
    eventsQuotaUsedCurrent: number;
    eventsQuotaMonthly?: number;
    retentionDays?: number;
    seatLimit?: number;
    lemonsqueezySubscriptionId?: string;
    lemonsqueezyCustomerId?: string;
    ssoConnectionId?: string;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
    invitations?: Array<InvitationResponseDto>;
    environments?: Array<EnvironmentResponseDto>;
};

export type UserOrganizationWithOrgResponseDto = {
    userId: string;
    orgId: string;
    role: string;
    joinedAt: string;
    deletedAt?: string;
    organization?: OrganizationResponseDto | null;
};

export type SwitchOrgDto = {
    organizationId: string;
};

export type SwitchActiveOrgResponseDto = {
    access_token: string;
    refresh_token: string;
    user?: UserResponseDto;
};

export type MessageResponseDto = {
    message: string;
};

export type OrganizationCreateResponseDto = {
    id: string;
    orgId: string;
    name: string;
    slug: string;
    description?: string;
    plan: string;
    ssoEnforced: boolean;
    eventsQuotaUsedCurrent: number;
    eventsQuotaMonthly?: number;
    retentionDays?: number;
    seatLimit?: number;
    lemonsqueezySubscriptionId?: string;
    lemonsqueezyCustomerId?: string;
    ssoConnectionId?: string;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
    invitations?: Array<InvitationResponseDto>;
    environments?: Array<EnvironmentResponseDto>;
    access_token: string;
    refresh_token: string;
};

export type OkResponseDto = {
    ok: boolean;
};

export type CreateInvitationDto = {
    invitedEmail: string;
    desired_role: 'user' | 'admin';
};

export type SuccessResponseDto = {
    success: boolean;
};

export type TransferOwnershipDto = {
    userId: string;
};

export type PlanFeaturesDto = {
    rbac?: boolean;
    auditLog?: boolean;
    sso?: boolean;
    customRetention?: boolean;
};

export type PlanVariantsDto = {
    monthly?: string;
    annual?: string;
};

export type PlanLimitsDto = {
    events: number | null;
    retentionDays: number | null;
    seats: number | null;
    features: PlanFeaturesDto;
    lemonsqueezyVariants?: PlanVariantsDto;
};

export type BillingPlansResponseDto = {
    /**
     * Plan id keyed by Plan enum value (free, pro, team, scale, selfhost).
     */
    plans: PlanLimitsDto;
};

export type BillingUsageResponseDto = {
    plan: string;
    used: number;
    limit?: number | null;
    retentionDays?: number | null;
    seats?: number | null;
    cycleStartedAt?: string | null;
    subscriptionStatus: 'active' | 'past_due' | 'paused' | 'trialing' | 'trial_expired';
    /**
     * ISO timestamp; null when no trial active
     */
    trialEndsAt?: string | null;
    /**
     * Whether a LemonSqueezy customer portal exists (a real subscription created one)
     */
    hasBillingPortal: boolean;
};

export type BillingCheckoutRequestDto = {
    plan: 'pro' | 'team';
    cadence?: 'monthly' | 'annual';
};

export type BillingCheckoutResponseDto = {
    url: string;
};

export type BillingPortalResponseDto = {
    url: string;
};

export type BillingWebhookResponseDto = {
    ok: boolean;
    deduped?: boolean;
    skipped?: string;
    enqueuedRetry?: boolean;
};

export type FeatureFlagsResponseDto = {
    environments: boolean;
    sentryIngest: boolean;
    asyncIngest: boolean;
    mcpServer: boolean;
};

export type CreateEnvironmentDto = {
    name: string;
    slug?: string;
    color?: string;
    isProduction?: boolean;
    isDefault?: boolean;
    cloneFromEnvId?: string;
};

export type UpdateEnvironmentDto = {
    name?: string;
    color?: string;
    requireConfirmationForDestructive?: boolean;
};

export type CreateEventDto = {
    identifier: string;
    payload: {
        [key: string]: unknown;
    };
    channel_id: string;
    agentId?: string;
    traceId?: string;
    spanId?: string;
    parentSpanId?: string;
    parentEventId?: string;
    eventType?: 'agent.start' | 'agent.end' | 'agent.message' | 'agent.tool_call.start' | 'agent.tool_call.end' | 'agent.error' | 'agent.handoff' | 'agent.llm.token' | 'agent.log' | 'app.log' | 'app.span' | 'custom';
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Environment slug override. Only honored when the API key has allowEnvironmentOverride=true.
     */
    environment?: string;
    /**
     * When true, wait for the event to be persisted to the DB before returning. Use only for audit-critical calls — the default async path returns in under a millisecond.
     */
    sync?: boolean;
};

export type EventIngestResponseDto = {
    /**
     * Alias of eventId, populated by the global IdAliasInterceptor.
     */
    id: string;
    eventId: string;
    identifier: string;
    dedupKey: string;
    createdAt: string;
    queued: boolean;
    duplicate?: boolean;
    environmentId?: string | null;
};

export type EventResponseDto = {
    id: string;
    eventId: string;
    orgId: string;
    appId: string;
    channelId: string;
    environmentId?: string;
    eventType: string;
    agentId?: string;
    traceId?: string;
    spanId?: string;
    parentSpanId?: string;
    parentEventId?: string;
    identifier?: string;
    payload?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    createdAt: string;
    occurredAt?: string;
    startTimeUnixNano?: string;
    endTimeUnixNano?: string;
    source?: string;
    semanticKind?: string;
    operationName?: string;
    durationMs?: number;
    status?: string;
    serviceName?: string;
    serviceVersion?: string;
    providerName?: string;
    requestModel?: string;
    responseModel?: string;
    toolName?: string;
    totalTokens?: number;
    costUsd?: number;
    updatedAt?: string;
    ttl?: number;
};

export type EventListMetaDto = {
    hasMore: boolean;
    cursor?: string | null;
};

export type EventListResponseDto = {
    data: Array<EventResponseDto>;
    meta: EventListMetaDto;
};

export type ChannelResponseDto = {
    id: string;
    channelId: string;
    orgId: string;
    appId: string;
    name: string;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
    app?: AppResponseDto;
};

export type AppResponseDto = {
    id: string;
    appId: string;
    orgId: string;
    name: string;
    creatorUserId?: string;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
    channels?: Array<ChannelResponseDto>;
};

export type CreateChannelDto = {
    name: string;
    appId: string;
};

export type CreateAppDto = {
    name: string;
};

export type CreateApiKeyDto = {
    name: string;
    organizationId: string;
    appId?: string;
    /**
     * Environment this key is bound to. All events published with this key will be tagged with this environment (unless allowEnvironmentOverride=true and the request specifies a different one).
     */
    environmentId?: string;
    /**
     * When true, the caller may override the env via X-Axonpush-Environment header or the event.environment field. Defaults to false for safety.
     */
    allowEnvironmentOverride?: boolean;
    scopes?: Array<'publish' | 'subscribe' | 'events:read' | 'traces:read' | 'apps:manage' | 'channels:manage' | 'webhooks:manage'>;
};

export type ApiKeyCreateResponseDto = {
    id: string;
    name: string;
    prefix?: string;
    /**
     * Raw API key, only returned at creation time
     */
    key: string;
    scopes: Array<'publish' | 'subscribe' | 'events:read' | 'traces:read' | 'apps:manage' | 'channels:manage' | 'webhooks:manage'>;
    environmentId?: string;
    allowEnvironmentOverride: boolean;
    createdAt: string;
};

export type ApiKeyResponseDto = {
    id: string;
    appId?: string;
    environmentId?: string;
    name: string;
    scopes: Array<'publish' | 'subscribe' | 'events:read' | 'traces:read' | 'apps:manage' | 'channels:manage' | 'webhooks:manage'>;
    allowEnvironmentOverride: boolean;
    purpose?: 'general' | 'ingest';
    prefix?: string;
    lastUsedAt?: string;
    createdAt: string;
};

export type CreatePublicTokenDto = {
    name: string;
    channelId: string;
    environmentId: string;
};

export type PublicIngestTokenCreateResponseDto = {
    id: string;
    tokenId: string;
    orgId: string;
    appId?: string;
    channelId?: string;
    environmentId?: string;
    name: string;
    scopes?: Array<string>;
    prefix?: string;
    lastUsedAt?: string;
    createdAt: string;
    revokedAt?: string;
    /**
     * Raw token, only returned at creation time
     */
    token: string;
};

export type PublicIngestTokenResponseDto = {
    id: string;
    tokenId: string;
    orgId: string;
    appId?: string;
    channelId?: string;
    environmentId?: string;
    name: string;
    scopes?: Array<string>;
    prefix?: string;
    lastUsedAt?: string;
    createdAt: string;
    revokedAt?: string;
};

export type CreateMcpTokenDto = {
    name: string;
    access: 'debug' | 'setup_debug';
};

export type McpTokenCreateResponseDto = {
    id: string;
    name: string;
    prefix: string;
    access: 'debug' | 'setup_debug';
    scopes: Array<string>;
    createdAt: string;
    expiresAt: string;
    lastUsedAt?: string;
    /**
     * Raw MCP token, returned only once at creation time
     */
    token: string;
};

export type McpTokenResponseDto = {
    id: string;
    name: string;
    prefix: string;
    access: 'debug' | 'setup_debug';
    scopes: Array<string>;
    createdAt: string;
    expiresAt: string;
    lastUsedAt?: string;
};

export type CreateWebhookEndpointDto = {
    url: string;
    channelId: string;
    secret?: string;
    /**
     * Event types to filter (null = all)
     */
    eventTypes?: Array<string>;
    description?: string;
};

export type WebhookEndpointCreateResponseDto = {
    id: string;
    endpointId: string;
    orgId?: string;
    channelId: string;
    url: string;
    eventTypes?: Array<string>;
    signingSecretPrefix?: string;
    hasSecret?: boolean;
    description?: string;
    active: boolean;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
    /**
     * Raw signing secret, only returned at creation time
     */
    rawSecret?: string;
    /**
     * Prefix of the signing secret
     */
    secretPrefix?: string | null;
};

export type WebhookEndpointResponseDto = {
    id: string;
    endpointId: string;
    orgId?: string;
    channelId: string;
    url: string;
    eventTypes?: Array<string>;
    signingSecretPrefix?: string;
    hasSecret?: boolean;
    description?: string;
    active: boolean;
    createdAt: string;
    updatedAt?: string;
    deletedAt?: string;
};

export type WebhookDeliveryResponseDto = {
    id: string;
    deliveryId: string;
    endpointId: string;
    eventId: string;
    status: 'pending' | 'success' | 'failed' | 'retrying';
    statusCode?: number;
    responseBody?: string;
    attempts: number;
    lastAttemptAt?: string;
    nextAttemptAt?: string;
    error?: string;
    createdAt: string;
};

export type WebhookIngestResponseDto = {
    status: string;
    eventId: string;
};

export type CreateExportDestinationDto = {
    name: string;
    /**
     * Environment slug this destination is scoped to (e.g. "prod")
     */
    envSlug: string;
    /**
     * OTLP/HTTP base URL (v1/logs and v1/traces are appended)
     */
    endpointUrl: string;
    /**
     * Header name -> value map (e.g. DD-API-KEY). Stored server-side, never returned.
     */
    headers?: {
        [key: string]: string;
    };
    signals: 'logs' | 'traces';
    /**
     * Allow-list of event types to export (empty = all types)
     */
    eventTypeFilter?: Array<string>;
    /**
     * service.name attribute stamped on exported resources
     */
    serviceName?: string;
    active?: boolean;
};

export type ExportDestinationResponseDto = {
    id: string;
    destinationId: string;
    orgId: string;
    envSlug: string;
    name: string;
    endpointUrl: string;
    /**
     * OTLP signals: logs and/or traces
     */
    signals: Array<string>;
    eventTypeFilter?: Array<string>;
    serviceName?: string;
    /**
     * Configured header names (values are masked)
     */
    headerKeys: Array<string>;
    active: boolean;
    createdAt: string;
    updatedAt?: string;
};

export type UpdateExportDestinationDto = {
    name?: string;
    endpointUrl?: string;
    /**
     * Replaces the stored header map. Never returned by the API.
     */
    headers?: {
        [key: string]: string;
    };
    signals?: 'logs' | 'traces';
    eventTypeFilter?: Array<string>;
    serviceName?: string;
    active?: boolean;
};

export type AuditLogActorDto = {
    id: string;
    first_name?: string;
    last_name?: string;
    email?: string;
    username?: string;
};

export type AuditLogResponseDto = {
    id: string;
    auditId: string;
    organizationId?: string;
    orgId?: string;
    actorId?: string | null;
    action: string;
    resourceType: string;
    resourceId?: string;
    metadata?: {
        [key: string]: unknown;
    } | null;
    ipAddress?: string | null;
    actor?: AuditLogActorDto | null;
    createdAt: string;
};

export type AuditLogListMetaDto = {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
};

export type AuditLogListResponseDto = {
    data: Array<AuditLogResponseDto>;
    meta: AuditLogListMetaDto;
};

export type HealthResponseDto = {
    status: string;
    timestamp: string;
    flags: {
        [key: string]: unknown;
    };
};

export type CreateReleaseDto = {
    version: string;
    projects?: Array<string>;
    dateReleased?: string;
};

export type ReleaseResponseDto = {
    orgId: string;
    version: string;
    projects?: string;
    dateCreated: string;
    dateReleased?: string;
    firstEventAt?: string;
    lastEventAt?: string;
};

export type ReleaseArtifactResponseDto = {
    orgId: string;
    version: string;
    artifactId: string;
    name: string;
    contentType?: string;
    sizeBytes: number;
    storagePath: string;
    sha256?: string;
    createdAt: string;
};

export type SsoConnectionResponseDto = {
    clientID: string;
    tenant?: string;
    product?: string;
    defaultRedirectUrl?: string;
    redirectUrl?: Array<string>;
};

export type ToggleEnforcementDto = {
    enforced: boolean;
};

export type SsoEnforcementResponseDto = {
    ok: boolean;
    enforced: boolean;
};

export type SsoAuthorizeResponseDto = {
    redirect_url: string;
};

export type SsoCallbackDto = {
    code: string;
};

export type AdminTotalsDto = {
    orgs: number;
    users: number;
};

export type AdminEventsDto = {
    /**
     * All-time events ingested (sum of per-org events_total counters)
     */
    total: number;
    /**
     * Events ingested today (UTC)
     */
    today: number;
    /**
     * Sum of every org’s events used in its current billing cycle
     */
    thisCycle: number;
};

export type CountByKeyDto = {
    /**
     * The grouped key, e.g. a plan or subscription status
     */
    key: string;
    count: number;
};

export type MrrByPlanDto = {
    plan: string;
    count: number;
    /**
     * Estimated monthly recurring revenue (USD) from this plan
     */
    mrrUsd: number;
};

export type AdminMrrDto = {
    /**
     * Approximate monthly recurring revenue (USD)
     */
    estimateUsd: number;
    payingOrgs: number;
    byPlan: Array<MrrByPlanDto>;
};

export type AdminOverviewDto = {
    totals: AdminTotalsDto;
    events: AdminEventsDto;
    /**
     * Org count grouped by plan
     */
    planDistribution: Array<CountByKeyDto>;
    /**
     * Org count grouped by subscription status
     */
    subscriptionStatusDistribution: Array<CountByKeyDto>;
    mrr: AdminMrrDto;
};

export type AdminRecentOrgDto = {
    orgId: string;
    name: string;
    slug: string;
    plan: string;
    subscriptionStatus: string | null;
    createdAt: string;
};

export type AdminRecentUserDto = {
    userId: string;
    email: string;
    organizationId: string | null;
    createdAt: string;
};

export type AdminSignupPointDto = {
    /**
     * UTC day, YYYY-MM-DD
     */
    day: string;
    orgs: number;
    users: number;
};

export type AdminSignupsDto = {
    recentOrgs: Array<AdminRecentOrgDto>;
    recentUsers: Array<AdminRecentUserDto>;
    /**
     * Signups per UTC day
     */
    series: Array<AdminSignupPointDto>;
};

export type AdminOrgListItemDto = {
    orgId: string;
    name: string;
    slug: string;
    plan: string;
    subscriptionStatus: string | null;
    eventsQuotaUsedCurrent: number | null;
    eventsQuotaMonthly: number | null;
    seatLimit: number | null;
    billingMonthlyAmountUsd: number | null;
    billingNotes: string | null;
    trialEndsAt: string | null;
    createdAt: string;
};

export type AdminOrgListDto = {
    /**
     * Number of orgs matching the query (before the response cap)
     */
    total: number;
    /**
     * True when results were capped and not all matches are returned
     */
    truncated: boolean;
    orgs: Array<AdminOrgListItemDto>;
};

export type AdminCreateCustomerDto = {
    name: string;
    slug: string;
    ownerEmail: string;
    plan: 'free' | 'pro' | 'team' | 'scale' | 'selfhost';
    trialDays: number;
    billingMonthlyAmountUsd: number;
    billingNotes?: string;
};

export type AdminOrgInvitationDto = {
    invitationId: string;
    invitedEmail: string;
    inviteRole: string;
    status: string;
    code: string;
    createdAt: string;
};

export type AdminCreateCustomerResponseDto = {
    org: AdminOrgListItemDto;
    invitation: AdminOrgInvitationDto;
};

export type AdminOrgLimitDto = {
    /**
     * Plan-derived default (null = unlimited)
     */
    planDefault: number | null;
    /**
     * Raw durable override: a number, -1 for unlimited, or null when unset
     */
    override: number | null;
    /**
     * Effective value in force (null = unlimited)
     */
    effective: number | null;
};

export type AdminOrgLimitsDto = {
    seats: AdminOrgLimitDto;
    retentionDays: AdminOrgLimitDto;
    eventsQuotaMonthly: AdminOrgLimitDto;
};

export type AdminOrgMemberDto = {
    userId: string;
    email: string;
    roles: Array<string>;
    createdAt: string;
};

export type AdminOrgDetailDto = {
    org: AdminOrgListItemDto;
    /**
     * Per-limit plan default / override / effective
     */
    limits: AdminOrgLimitsDto;
    members: Array<AdminOrgMemberDto>;
    invitations: Array<AdminOrgInvitationDto>;
};

export type AdminSetPlanDto = {
    plan: 'free' | 'pro' | 'team' | 'scale' | 'selfhost';
};

export type AdminOrgMutationResponseDto = {
    ok: boolean;
    subscriptionStatus: string | null;
    plan: string | null;
};

export type AdminSetLimitsDto = {
    /**
     * Seat limit override: >=1 for a value, -1 for unlimited, null to clear
     */
    seatLimit?: number | null;
    /**
     * Retention days override: >=1 for a value, -1 for unlimited, null to clear
     */
    retentionDays?: number | null;
    /**
     * Monthly events quota override: >=0 for a value, -1 for unlimited, null to clear
     */
    eventsQuotaMonthly?: number | null;
};

export type AdminSetStatusDto = {
    subscriptionStatus: 'active' | 'past_due' | 'paused' | 'trialing' | 'trial_expired';
};

export type AdminSetTrialDto = {
    /**
     * Trial length in days from now
     */
    days: number;
};

export type AdminUpdateBillingDto = {
    billingMonthlyAmountUsd: number;
    billingNotes?: string;
};

export type AdminUserListItemDto = {
    userId: string;
    email: string;
    firstName: string | null;
    lastName: string | null;
    organizationId: string | null;
    disabledAt: string | null;
    createdAt: string;
    trialStartedAt: string | null;
    trialEndsAt: string | null;
};

export type AdminUserListDto = {
    total: number;
    truncated: boolean;
    users: Array<AdminUserListItemDto>;
};

export type AdminOkResponseDto = {
    ok: boolean;
};

export type AdminBillingEventListItemDto = {
    id: string;
    orgId: string;
    externalId: string;
    eventName: string;
    createdAt: string;
    processedAt: string | null;
    error: string | null;
};

export type AdminBillingEventListDto = {
    events: Array<AdminBillingEventListItemDto>;
};

export type AdminBillingEventReplayResponseDto = {
    ok: boolean;
    error: string | null;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: string;
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AuthControllerSignUpData = {
    body: UserCreateDto;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignUpResponses = {
    201: UserResponseDto;
};

export type AuthControllerSignUpResponse = AuthControllerSignUpResponses[keyof AuthControllerSignUpResponses];

export type AuthControllerSignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/signin';
};

export type AuthControllerSignInResponses = {
    200: AuthTokensResponseDto;
    201: unknown;
};

export type AuthControllerSignInResponse = AuthControllerSignInResponses[keyof AuthControllerSignInResponses];

export type AuthControllerGoogleAuthData = {
    body: GoogleAuthDto;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleAuthResponses = {
    200: GoogleAuthResponseDto;
    201: {
        [key: string]: unknown;
    };
};

export type AuthControllerGoogleAuthResponse = AuthControllerGoogleAuthResponses[keyof AuthControllerGoogleAuthResponses];

export type AuthControllerSetupOrgData = {
    body: SetupOrgDto;
    path?: never;
    query?: never;
    url: '/auth/setup-org';
};

export type AuthControllerSetupOrgResponses = {
    200: AuthTokensResponseDto;
    201: unknown;
};

export type AuthControllerSetupOrgResponse = AuthControllerSetupOrgResponses[keyof AuthControllerSetupOrgResponses];

export type AuthControllerRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    200: AuthTokensResponseDto;
    201: unknown;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type IotCredentialsControllerGetCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/iot-credentials';
};

export type IotCredentialsControllerGetCredentialsResponses = {
    200: IotCredentialsResponseDto;
};

export type IotCredentialsControllerGetCredentialsResponse = IotCredentialsControllerGetCredentialsResponses[keyof IotCredentialsControllerGetCredentialsResponses];

export type UserControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerGetMeResponses = {
    200: UserResponseDto;
};

export type UserControllerGetMeResponse = UserControllerGetMeResponses[keyof UserControllerGetMeResponses];

export type UserControllerUpdateMeData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserControllerUpdateMeResponses = {
    200: UserResponseDto;
};

export type UserControllerUpdateMeResponse = UserControllerUpdateMeResponses[keyof UserControllerUpdateMeResponses];

export type UserControllerGetMyOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/organizations';
};

export type UserControllerGetMyOrganizationsResponses = {
    200: Array<UserOrganizationWithOrgResponseDto>;
};

export type UserControllerGetMyOrganizationsResponse = UserControllerGetMyOrganizationsResponses[keyof UserControllerGetMyOrganizationsResponses];

export type UserControllerSwitchActiveOrgData = {
    body: SwitchOrgDto;
    path?: never;
    query?: never;
    url: '/users/me/active-org';
};

export type UserControllerSwitchActiveOrgResponses = {
    200: SwitchActiveOrgResponseDto;
};

export type UserControllerSwitchActiveOrgResponse = UserControllerSwitchActiveOrgResponses[keyof UserControllerSwitchActiveOrgResponses];

export type UserControllerGetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UserControllerGetUsersResponses = {
    200: Array<UserResponseDto>;
};

export type UserControllerGetUsersResponse = UserControllerGetUsersResponses[keyof UserControllerGetUsersResponses];

export type UserControllerDeleteUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerDeleteUserResponses = {
    200: MessageResponseDto;
};

export type UserControllerDeleteUserResponse = UserControllerDeleteUserResponses[keyof UserControllerDeleteUserResponses];

export type UserControllerUpdateUserData = {
    body: UpdateProfileDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UserControllerUpdateUserResponses = {
    200: UserResponseDto;
};

export type UserControllerUpdateUserResponse = UserControllerUpdateUserResponses[keyof UserControllerUpdateUserResponses];

export type OrganizationControllerGetAllOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type OrganizationControllerGetAllOrganizationsResponses = {
    200: Array<OrganizationResponseDto>;
};

export type OrganizationControllerGetAllOrganizationsResponse = OrganizationControllerGetAllOrganizationsResponses[keyof OrganizationControllerGetAllOrganizationsResponses];

export type OrganizationControllerCreateOrganizationData = {
    body: CreateOrganizationDto;
    path?: never;
    query?: never;
    url: '/organizations';
};

export type OrganizationControllerCreateOrganizationResponses = {
    201: OrganizationCreateResponseDto;
};

export type OrganizationControllerCreateOrganizationResponse = OrganizationControllerCreateOrganizationResponses[keyof OrganizationControllerCreateOrganizationResponses];

export type OrganizationControllerDeleteOrganizationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type OrganizationControllerDeleteOrganizationResponses = {
    200: OkResponseDto;
};

export type OrganizationControllerDeleteOrganizationResponse = OrganizationControllerDeleteOrganizationResponses[keyof OrganizationControllerDeleteOrganizationResponses];

export type OrganizationControllerGetOrganizationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type OrganizationControllerGetOrganizationResponses = {
    200: OrganizationResponseDto;
};

export type OrganizationControllerGetOrganizationResponse = OrganizationControllerGetOrganizationResponses[keyof OrganizationControllerGetOrganizationResponses];

export type OrganizationControllerEditOrganizationData = {
    body: CreateOrganizationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}';
};

export type OrganizationControllerEditOrganizationResponses = {
    200: OkResponseDto;
};

export type OrganizationControllerEditOrganizationResponse = OrganizationControllerEditOrganizationResponses[keyof OrganizationControllerEditOrganizationResponses];

export type OrganizationControllerGetTelemetryPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/telemetry-policy';
};

export type OrganizationControllerGetTelemetryPolicyResponses = {
    200: unknown;
};

export type OrganizationControllerUpdateTelemetryPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/telemetry-policy';
};

export type OrganizationControllerUpdateTelemetryPolicyResponses = {
    200: unknown;
};

export type OrganizationControllerCreateInvitationData = {
    body: CreateInvitationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/invitations';
};

export type OrganizationControllerCreateInvitationResponses = {
    201: InvitationResponseDto;
};

export type OrganizationControllerCreateInvitationResponse = OrganizationControllerCreateInvitationResponses[keyof OrganizationControllerCreateInvitationResponses];

export type OrganizationControllerRemoveMemberData = {
    body?: never;
    path: {
        id: string;
        userId: string;
    };
    query?: never;
    url: '/organizations/{id}/members/{userId}';
};

export type OrganizationControllerRemoveMemberResponses = {
    200: SuccessResponseDto;
};

export type OrganizationControllerRemoveMemberResponse = OrganizationControllerRemoveMemberResponses[keyof OrganizationControllerRemoveMemberResponses];

export type OrganizationControllerTransferOwnershipData = {
    body: TransferOwnershipDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/organizations/{id}/transfer-ownership';
};

export type OrganizationControllerTransferOwnershipResponses = {
    200: SuccessResponseDto;
    201: unknown;
};

export type OrganizationControllerTransferOwnershipResponse = OrganizationControllerTransferOwnershipResponses[keyof OrganizationControllerTransferOwnershipResponses];

export type OrganizationControllerDeleteInvitationData = {
    body?: never;
    path: {
        id: string;
        invitationId: string;
    };
    query?: never;
    url: '/organizations/{id}/invitations/{invitationId}';
};

export type OrganizationControllerDeleteInvitationResponses = {
    200: SuccessResponseDto;
};

export type OrganizationControllerDeleteInvitationResponse = OrganizationControllerDeleteInvitationResponses[keyof OrganizationControllerDeleteInvitationResponses];

export type BillingControllerGetPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/plans';
};

export type BillingControllerGetPlansResponses = {
    200: BillingPlansResponseDto;
};

export type BillingControllerGetPlansResponse = BillingControllerGetPlansResponses[keyof BillingControllerGetPlansResponses];

export type BillingControllerGetUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/usage';
};

export type BillingControllerGetUsageResponses = {
    200: BillingUsageResponseDto;
};

export type BillingControllerGetUsageResponse = BillingControllerGetUsageResponses[keyof BillingControllerGetUsageResponses];

export type BillingControllerCreateCheckoutData = {
    body: BillingCheckoutRequestDto;
    path?: never;
    query?: never;
    url: '/billing/checkout';
};

export type BillingControllerCreateCheckoutResponses = {
    201: BillingCheckoutResponseDto;
};

export type BillingControllerCreateCheckoutResponse = BillingControllerCreateCheckoutResponses[keyof BillingControllerCreateCheckoutResponses];

export type BillingControllerGetPortalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/portal';
};

export type BillingControllerGetPortalResponses = {
    200: BillingPortalResponseDto;
};

export type BillingControllerGetPortalResponse = BillingControllerGetPortalResponses[keyof BillingControllerGetPortalResponses];

export type BillingControllerHandleWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/billing/webhook';
};

export type BillingControllerHandleWebhookResponses = {
    201: BillingWebhookResponseDto;
};

export type BillingControllerHandleWebhookResponse = BillingControllerHandleWebhookResponses[keyof BillingControllerHandleWebhookResponses];

export type FeatureFlagsControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/feature-flags/me';
};

export type FeatureFlagsControllerMeResponses = {
    200: FeatureFlagsResponseDto;
};

export type FeatureFlagsControllerMeResponse = FeatureFlagsControllerMeResponses[keyof FeatureFlagsControllerMeResponses];

export type CapabilitiesControllerGetCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/capabilities';
};

export type CapabilitiesControllerGetCapabilitiesResponses = {
    /**
     * Backend-authoritative product and deployment capabilities
     */
    200: unknown;
};

export type EnvironmentControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environments';
};

export type EnvironmentControllerListResponses = {
    200: Array<EnvironmentResponseDto>;
};

export type EnvironmentControllerListResponse = EnvironmentControllerListResponses[keyof EnvironmentControllerListResponses];

export type EnvironmentControllerCreateData = {
    body: CreateEnvironmentDto;
    path?: never;
    query?: never;
    url: '/environments';
};

export type EnvironmentControllerCreateResponses = {
    201: EnvironmentResponseDto;
};

export type EnvironmentControllerCreateResponse = EnvironmentControllerCreateResponses[keyof EnvironmentControllerCreateResponses];

export type EnvironmentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/environments/{id}';
};

export type EnvironmentControllerRemoveResponses = {
    200: OkResponseDto;
};

export type EnvironmentControllerRemoveResponse = EnvironmentControllerRemoveResponses[keyof EnvironmentControllerRemoveResponses];

export type EnvironmentControllerUpdateData = {
    body: UpdateEnvironmentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/environments/{id}';
};

export type EnvironmentControllerUpdateResponses = {
    200: EnvironmentResponseDto;
};

export type EnvironmentControllerUpdateResponse = EnvironmentControllerUpdateResponses[keyof EnvironmentControllerUpdateResponses];

export type EnvironmentControllerPromoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/environments/{id}/promote-to-default';
};

export type EnvironmentControllerPromoteResponses = {
    200: EnvironmentResponseDto;
    201: {
        [key: string]: unknown;
    };
};

export type EnvironmentControllerPromoteResponse = EnvironmentControllerPromoteResponses[keyof EnvironmentControllerPromoteResponses];

export type EventControllerCreateEventData = {
    body: CreateEventDto;
    headers?: {
        /**
         * Stripe-style client-supplied idempotency key (1–255 ASCII-printable chars). Cached response replay for retried requests.
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/event';
};

export type EventControllerCreateEventResponses = {
    201: EventIngestResponseDto;
};

export type EventControllerCreateEventResponse = EventControllerCreateEventResponses[keyof EventControllerCreateEventResponses];

export type EventControllerListEventsData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: {
        payloadFilter?: string;
        /**
         * Page size, 1-1000. Defaults to 100.
         */
        limit?: number;
        cursor?: string;
        /**
         * ISO 8601 datetime (exclusive upper bound).
         */
        until?: string;
        /**
         * ISO 8601 datetime (inclusive lower bound).
         */
        since?: string;
        traceId?: string;
        agentId?: string;
        eventType?: Array<string>;
        /**
         * Environment slug. Resolved server-side to environmentId.
         */
        environment?: string;
    };
    url: '/event/{channelId}/list';
};

export type EventControllerListEventsResponses = {
    200: EventListResponseDto;
};

export type EventControllerListEventsResponse = EventControllerListEventsResponses[keyof EventControllerListEventsResponses];

export type EventsSearchControllerSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive free-text match over event fields and retained payload.
         */
        query?: string;
        /**
         * Filter by ingest source (sdk, otlp, sentry, webhook, mcp or custom).
         */
        source?: string;
        /**
         * JSON-path / dotted filter applied to the event payload.
         */
        payloadFilter?: string;
        /**
         * Page size, 1-1000. Defaults to 100.
         */
        limit?: number;
        /**
         * Opaque pagination cursor returned by a previous call.
         */
        cursor?: string;
        /**
         * ISO 8601 datetime (exclusive upper bound).
         */
        until?: string;
        /**
         * ISO 8601 datetime (inclusive lower bound).
         */
        since?: string;
        traceId?: string;
        agentId?: string;
        /**
         * Repeat or comma-separate to filter by multiple event types.
         */
        eventType?: Array<string>;
        channelId?: string;
        appId?: string;
        /**
         * Environment slug. Resolved server-side to environmentId.
         */
        environment?: string;
    };
    url: '/events/search';
};

export type EventsSearchControllerSearchResponses = {
    200: EventListResponseDto;
};

export type EventsSearchControllerSearchResponse = EventsSearchControllerSearchResponses[keyof EventsSearchControllerSearchResponses];

export type ChannelControllerListChannelsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * App UUID to scope the listing.
         */
        appId: string;
    };
    url: '/channel';
};

export type ChannelControllerListChannelsResponses = {
    200: Array<ChannelResponseDto>;
};

export type ChannelControllerListChannelsResponse = ChannelControllerListChannelsResponses[keyof ChannelControllerListChannelsResponses];

export type ChannelControllerCreateChannelData = {
    body: CreateChannelDto;
    path?: never;
    query?: never;
    url: '/channel';
};

export type ChannelControllerCreateChannelResponses = {
    201: ChannelResponseDto;
};

export type ChannelControllerCreateChannelResponse = ChannelControllerCreateChannelResponses[keyof ChannelControllerCreateChannelResponses];

export type ChannelControllerDeleteChannelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/channel/{id}';
};

export type ChannelControllerDeleteChannelResponses = {
    200: OkResponseDto;
};

export type ChannelControllerDeleteChannelResponse = ChannelControllerDeleteChannelResponses[keyof ChannelControllerDeleteChannelResponses];

export type ChannelControllerGetChannelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/channel/{id}';
};

export type ChannelControllerGetChannelResponses = {
    200: ChannelResponseDto;
};

export type ChannelControllerGetChannelResponse = ChannelControllerGetChannelResponses[keyof ChannelControllerGetChannelResponses];

export type ChannelControllerUpdateChannelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/channel/{id}';
};

export type ChannelControllerUpdateChannelResponses = {
    200: OkResponseDto;
};

export type ChannelControllerUpdateChannelResponse = ChannelControllerUpdateChannelResponses[keyof ChannelControllerUpdateChannelResponses];

export type AppsControllerGetAllAppsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/apps';
};

export type AppsControllerGetAllAppsResponses = {
    200: Array<AppResponseDto>;
};

export type AppsControllerGetAllAppsResponse = AppsControllerGetAllAppsResponses[keyof AppsControllerGetAllAppsResponses];

export type AppsControllerCreateAppData = {
    body: CreateAppDto;
    path?: never;
    query?: never;
    url: '/apps';
};

export type AppsControllerCreateAppResponses = {
    201: AppResponseDto;
};

export type AppsControllerCreateAppResponse = AppsControllerCreateAppResponses[keyof AppsControllerCreateAppResponses];

export type AppsControllerDeleteAppData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}';
};

export type AppsControllerDeleteAppResponses = {
    200: OkResponseDto;
};

export type AppsControllerDeleteAppResponse = AppsControllerDeleteAppResponses[keyof AppsControllerDeleteAppResponses];

export type AppsControllerGetAppData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}';
};

export type AppsControllerGetAppResponses = {
    200: AppResponseDto;
};

export type AppsControllerGetAppResponse = AppsControllerGetAppResponses[keyof AppsControllerGetAppResponses];

export type AppsControllerEditAppData = {
    body: CreateAppDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/apps/{id}';
};

export type AppsControllerEditAppResponses = {
    200: OkResponseDto;
};

export type AppsControllerEditAppResponse = AppsControllerEditAppResponses[keyof AppsControllerEditAppResponses];

export type ApiKeyControllerListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ApiKeyControllerListApiKeysResponses = {
    200: Array<ApiKeyResponseDto>;
};

export type ApiKeyControllerListApiKeysResponse = ApiKeyControllerListApiKeysResponses[keyof ApiKeyControllerListApiKeysResponses];

export type ApiKeyControllerCreateApiKeyData = {
    body: CreateApiKeyDto;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ApiKeyControllerCreateApiKeyResponses = {
    201: ApiKeyCreateResponseDto;
};

export type ApiKeyControllerCreateApiKeyResponse = ApiKeyControllerCreateApiKeyResponses[keyof ApiKeyControllerCreateApiKeyResponses];

export type ApiKeyControllerRevokeApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type ApiKeyControllerRevokeApiKeyResponses = {
    200: MessageResponseDto;
};

export type ApiKeyControllerRevokeApiKeyResponse = ApiKeyControllerRevokeApiKeyResponses[keyof ApiKeyControllerRevokeApiKeyResponses];

export type PublicIngestTokenControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/public-tokens';
};

export type PublicIngestTokenControllerListResponses = {
    200: Array<PublicIngestTokenResponseDto>;
};

export type PublicIngestTokenControllerListResponse = PublicIngestTokenControllerListResponses[keyof PublicIngestTokenControllerListResponses];

export type PublicIngestTokenControllerCreateData = {
    body: CreatePublicTokenDto;
    path?: never;
    query?: never;
    url: '/public-tokens';
};

export type PublicIngestTokenControllerCreateResponses = {
    201: PublicIngestTokenCreateResponseDto;
};

export type PublicIngestTokenControllerCreateResponse = PublicIngestTokenControllerCreateResponses[keyof PublicIngestTokenControllerCreateResponses];

export type PublicIngestTokenControllerRevokeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/public-tokens/{id}';
};

export type PublicIngestTokenControllerRevokeResponses = {
    200: OkResponseDto;
};

export type PublicIngestTokenControllerRevokeResponse = PublicIngestTokenControllerRevokeResponses[keyof PublicIngestTokenControllerRevokeResponses];

export type McpControllerHandleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mcp';
};

export type McpControllerHandleResponses = {
    200: unknown;
};

export type McpTokenControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/mcp-tokens';
};

export type McpTokenControllerListResponses = {
    200: Array<McpTokenResponseDto>;
};

export type McpTokenControllerListResponse = McpTokenControllerListResponses[keyof McpTokenControllerListResponses];

export type McpTokenControllerCreateData = {
    body: CreateMcpTokenDto;
    path?: never;
    query?: never;
    url: '/users/me/mcp-tokens';
};

export type McpTokenControllerCreateResponses = {
    201: McpTokenCreateResponseDto;
};

export type McpTokenControllerCreateResponse = McpTokenControllerCreateResponses[keyof McpTokenControllerCreateResponses];

export type McpTokenControllerRevokeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/me/mcp-tokens/{id}';
};

export type McpTokenControllerRevokeResponses = {
    200: MessageResponseDto;
};

export type McpTokenControllerRevokeResponse = McpTokenControllerRevokeResponses[keyof McpTokenControllerRevokeResponses];

export type TraceControllerListTracesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        appId?: string;
        environment?: string;
    };
    url: '/traces';
};

export type TraceControllerListTracesResponses = {
    /**
     * Paginated list of trace summaries
     */
    200: {
        data: Array<{
            traceId: string;
            eventCount: number;
            agents: Array<string>;
            eventTypes: Array<string>;
            startTime: string;
            endTime: string;
            duration: number;
            errorCount: number;
            toolCallCount: number;
            handoffCount: number;
            totalTokens?: number;
            /**
             * Known reported/estimated cost. Omitted when pricing is unknown.
             */
            costUsd?: number | null;
            status?: string;
        }>;
        meta: {
            page: number;
            limit: number;
            hasMore: boolean;
        };
    };
};

export type TraceControllerListTracesResponse = TraceControllerListTracesResponses[keyof TraceControllerListTracesResponses];

export type TraceControllerGetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: {
        appId?: string;
        environment?: string;
    };
    url: '/traces/stats';
};

export type TraceControllerGetDashboardStatsResponses = {
    /**
     * Aggregated dashboard stats for the caller organization
     */
    200: {
        totalEvents: number;
        eventsToday: number;
        totalTraces: number;
        tracesToday: number;
        errorCount: number;
        errorRate: number;
        avgTraceDuration: number;
        eventsByHour: Array<{
            hour?: string;
            count?: number;
        }>;
    };
};

export type TraceControllerGetDashboardStatsResponse = TraceControllerGetDashboardStatsResponses[keyof TraceControllerGetDashboardStatsResponses];

export type TraceControllerGetTraceEventsData = {
    body?: never;
    path: {
        traceId: string;
    };
    query?: {
        appId?: string;
        environment?: string;
    };
    url: '/traces/{traceId}/events';
};

export type TraceControllerGetTraceEventsResponses = {
    /**
     * All events belonging to a trace, ordered by authoritative occurrence time
     */
    200: Array<EventResponseDto>;
};

export type TraceControllerGetTraceEventsResponse = TraceControllerGetTraceEventsResponses[keyof TraceControllerGetTraceEventsResponses];

export type TraceControllerGetTraceSummaryData = {
    body?: never;
    path: {
        traceId: string;
    };
    query?: {
        appId?: string;
        environment?: string;
    };
    url: '/traces/{traceId}/summary';
};

export type TraceControllerGetTraceSummaryResponses = {
    /**
     * Aggregated summary for a single trace
     */
    200: {
        traceId: string;
        eventCount: number;
        agents: Array<string>;
        eventTypes: Array<string>;
        startTime: string;
        endTime: string;
        duration: number;
        errorCount: number;
        toolCallCount: number;
        handoffCount: number;
        totalTokens?: number;
        /**
         * Known reported/estimated cost. Omitted when pricing is unknown.
         */
        costUsd?: number | null;
        status?: string;
    };
};

export type TraceControllerGetTraceSummaryResponse = TraceControllerGetTraceSummaryResponses[keyof TraceControllerGetTraceSummaryResponses];

export type WebhookControllerCreateEndpointData = {
    body: CreateWebhookEndpointDto;
    path?: never;
    query?: never;
    url: '/webhooks/endpoints';
};

export type WebhookControllerCreateEndpointResponses = {
    201: WebhookEndpointCreateResponseDto;
};

export type WebhookControllerCreateEndpointResponse = WebhookControllerCreateEndpointResponses[keyof WebhookControllerCreateEndpointResponses];

export type WebhookControllerListEndpointsData = {
    body?: never;
    path: {
        channelId: string;
    };
    query?: never;
    url: '/webhooks/endpoints/channel/{channelId}';
};

export type WebhookControllerListEndpointsResponses = {
    200: Array<WebhookEndpointResponseDto>;
};

export type WebhookControllerListEndpointsResponse = WebhookControllerListEndpointsResponses[keyof WebhookControllerListEndpointsResponses];

export type WebhookControllerDeleteEndpointData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/webhooks/endpoints/{id}';
};

export type WebhookControllerDeleteEndpointResponses = {
    200: MessageResponseDto;
};

export type WebhookControllerDeleteEndpointResponse = WebhookControllerDeleteEndpointResponses[keyof WebhookControllerDeleteEndpointResponses];

export type WebhookControllerGetDeliveriesData = {
    body?: never;
    path: {
        endpointId: string;
    };
    query?: never;
    url: '/webhooks/deliveries/{endpointId}';
};

export type WebhookControllerGetDeliveriesResponses = {
    200: Array<WebhookDeliveryResponseDto>;
};

export type WebhookControllerGetDeliveriesResponse = WebhookControllerGetDeliveriesResponses[keyof WebhookControllerGetDeliveriesResponses];

export type WebhookControllerIngestWebhookData = {
    body?: never;
    headers: {
        'X-Webhook-Signature': string;
    };
    path: {
        endpointId: string;
    };
    query?: never;
    url: '/webhooks/ingest/{endpointId}';
};

export type WebhookControllerIngestWebhookResponses = {
    201: WebhookIngestResponseDto;
};

export type WebhookControllerIngestWebhookResponse = WebhookControllerIngestWebhookResponses[keyof WebhookControllerIngestWebhookResponses];

export type ExportControllerListData = {
    body?: never;
    path?: never;
    query: {
        envSlug: string;
    };
    url: '/export-destinations';
};

export type ExportControllerListResponses = {
    200: Array<ExportDestinationResponseDto>;
};

export type ExportControllerListResponse = ExportControllerListResponses[keyof ExportControllerListResponses];

export type ExportControllerCreateData = {
    body: CreateExportDestinationDto;
    path?: never;
    query?: never;
    url: '/export-destinations';
};

export type ExportControllerCreateResponses = {
    201: ExportDestinationResponseDto;
};

export type ExportControllerCreateResponse = ExportControllerCreateResponses[keyof ExportControllerCreateResponses];

export type ExportControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/export-destinations/{id}';
};

export type ExportControllerRemoveResponses = {
    200: MessageResponseDto;
};

export type ExportControllerRemoveResponse = ExportControllerRemoveResponses[keyof ExportControllerRemoveResponses];

export type ExportControllerGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/export-destinations/{id}';
};

export type ExportControllerGetResponses = {
    200: ExportDestinationResponseDto;
};

export type ExportControllerGetResponse = ExportControllerGetResponses[keyof ExportControllerGetResponses];

export type ExportControllerUpdateData = {
    body: UpdateExportDestinationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/export-destinations/{id}';
};

export type ExportControllerUpdateResponses = {
    200: ExportDestinationResponseDto;
};

export type ExportControllerUpdateResponse = ExportControllerUpdateResponses[keyof ExportControllerUpdateResponses];

export type AuditLogControllerListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        action?: string;
        resourceType?: string;
        actorId?: string;
        from?: string;
        to?: string;
    };
    url: '/audit-logs';
};

export type AuditLogControllerListAuditLogsResponses = {
    /**
     * Paginated list of audit log entries for the caller organization
     */
    200: AuditLogListResponseDto;
};

export type AuditLogControllerListAuditLogsResponse = AuditLogControllerListAuditLogsResponses[keyof AuditLogControllerListAuditLogsResponses];

export type OtlpControllerIngestLogsData = {
    body?: never;
    headers: {
        'X-Axonpush-Channel': string;
        'Idempotency-Key'?: string;
        'X-Axonpush-Environment'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/logs';
};

export type OtlpControllerIngestLogsResponses = {
    200: unknown;
    201: {
        [key: string]: unknown;
    };
};

export type OtlpControllerIngestLogsResponse = OtlpControllerIngestLogsResponses[keyof OtlpControllerIngestLogsResponses];

export type OtlpControllerIngestTracesData = {
    body?: never;
    headers: {
        'X-Axonpush-Channel': string;
        'Idempotency-Key'?: string;
        'X-Axonpush-Environment'?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/traces';
};

export type OtlpControllerIngestTracesResponses = {
    200: unknown;
    201: {
        [key: string]: unknown;
    };
};

export type OtlpControllerIngestTracesResponse = OtlpControllerIngestTracesResponses[keyof OtlpControllerIngestTracesResponses];

export type HealthControllerCheckData = {
    body?: never;
    path?: never;
    query?: {
        deep?: boolean;
    };
    url: '/health';
};

export type HealthControllerCheckResponses = {
    200: HealthResponseDto;
};

export type HealthControllerCheckResponse = HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type ReleaseControllerListData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/releases';
};

export type ReleaseControllerListResponses = {
    200: Array<ReleaseResponseDto>;
};

export type ReleaseControllerListResponse = ReleaseControllerListResponses[keyof ReleaseControllerListResponses];

export type ReleaseControllerCreateData = {
    body: CreateReleaseDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/organizations/{orgId}/releases';
};

export type ReleaseControllerCreateResponses = {
    201: ReleaseResponseDto;
};

export type ReleaseControllerCreateResponse = ReleaseControllerCreateResponses[keyof ReleaseControllerCreateResponses];

export type ReleaseControllerUploadArtifactData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/releases/{version}/artifacts';
};

export type ReleaseControllerUploadArtifactResponses = {
    201: ReleaseArtifactResponseDto;
};

export type ReleaseControllerUploadArtifactResponse = ReleaseControllerUploadArtifactResponses[keyof ReleaseControllerUploadArtifactResponses];

export type SentryControllerIngestEnvelopeData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/{projectId}/envelope';
};

export type SentryControllerIngestEnvelopeResponses = {
    201: unknown;
};

export type SentryControllerIngestStoreData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/{projectId}/store';
};

export type SentryControllerIngestStoreResponses = {
    201: unknown;
};

export type SentryControllerIngestSecurityData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/{projectId}/security';
};

export type SentryControllerIngestSecurityResponses = {
    201: unknown;
};

export type SentryControllerIngestMinidumpData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/{projectId}/minidump';
};

export type SentryControllerIngestMinidumpResponses = {
    201: unknown;
};

export type SsoControllerGetConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sso/connections';
};

export type SsoControllerGetConnectionsResponses = {
    200: Array<SsoConnectionResponseDto>;
};

export type SsoControllerGetConnectionsResponse = SsoControllerGetConnectionsResponses[keyof SsoControllerGetConnectionsResponses];

export type SsoControllerCreateConnectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sso/connections';
};

export type SsoControllerCreateConnectionResponses = {
    201: SsoConnectionResponseDto;
};

export type SsoControllerCreateConnectionResponse = SsoControllerCreateConnectionResponses[keyof SsoControllerCreateConnectionResponses];

export type SsoControllerDeleteConnectionData = {
    body?: never;
    path: {
        clientID: string;
    };
    query?: never;
    url: '/sso/connections/{clientID}';
};

export type SsoControllerDeleteConnectionResponses = {
    200: OkResponseDto;
};

export type SsoControllerDeleteConnectionResponse = SsoControllerDeleteConnectionResponses[keyof SsoControllerDeleteConnectionResponses];

export type SsoControllerToggleEnforcementData = {
    body: ToggleEnforcementDto;
    path?: never;
    query?: never;
    url: '/sso/enforcement';
};

export type SsoControllerToggleEnforcementResponses = {
    200: SsoEnforcementResponseDto;
};

export type SsoControllerToggleEnforcementResponse = SsoControllerToggleEnforcementResponses[keyof SsoControllerToggleEnforcementResponses];

export type SsoControllerAuthorizeData = {
    body?: never;
    path?: never;
    query?: {
        email?: string;
        org_slug?: string;
    };
    url: '/auth/sso/authorize';
};

export type SsoControllerAuthorizeResponses = {
    200: SsoAuthorizeResponseDto;
};

export type SsoControllerAuthorizeResponse = SsoControllerAuthorizeResponses[keyof SsoControllerAuthorizeResponses];

export type SsoControllerCallbackData = {
    body: SsoCallbackDto;
    path?: never;
    query?: never;
    url: '/auth/sso/callback';
};

export type SsoControllerCallbackResponses = {
    201: AuthTokensResponseDto;
};

export type SsoControllerCallbackResponse = SsoControllerCallbackResponses[keyof SsoControllerCallbackResponses];

export type SsoControllerSamlAcsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sso/acs';
};

export type SsoControllerSamlAcsResponses = {
    201: unknown;
};

export type AdminControllerGetOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/overview';
};

export type AdminControllerGetOverviewResponses = {
    200: AdminOverviewDto;
};

export type AdminControllerGetOverviewResponse = AdminControllerGetOverviewResponses[keyof AdminControllerGetOverviewResponses];

export type AdminControllerGetSignupsData = {
    body?: never;
    path?: never;
    query: {
        days: string;
    };
    url: '/admin/signups';
};

export type AdminControllerGetSignupsResponses = {
    200: AdminSignupsDto;
};

export type AdminControllerGetSignupsResponse = AdminControllerGetSignupsResponses[keyof AdminControllerGetSignupsResponses];

export type AdminControllerGetOrgsData = {
    body?: never;
    path?: never;
    query: {
        search: string;
    };
    url: '/admin/orgs';
};

export type AdminControllerGetOrgsResponses = {
    200: AdminOrgListDto;
};

export type AdminControllerGetOrgsResponse = AdminControllerGetOrgsResponses[keyof AdminControllerGetOrgsResponses];

export type AdminControllerCreateCustomerData = {
    body: AdminCreateCustomerDto;
    path?: never;
    query?: never;
    url: '/admin/customers';
};

export type AdminControllerCreateCustomerResponses = {
    201: AdminCreateCustomerResponseDto;
};

export type AdminControllerCreateCustomerResponse = AdminControllerCreateCustomerResponses[keyof AdminControllerCreateCustomerResponses];

export type AdminControllerGetOrgData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/orgs/{id}';
};

export type AdminControllerGetOrgResponses = {
    200: AdminOrgDetailDto;
};

export type AdminControllerGetOrgResponse = AdminControllerGetOrgResponses[keyof AdminControllerGetOrgResponses];

export type AdminControllerSetOrgPlanData = {
    body: AdminSetPlanDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/plan';
};

export type AdminControllerSetOrgPlanResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerSetOrgPlanResponse = AdminControllerSetOrgPlanResponses[keyof AdminControllerSetOrgPlanResponses];

export type AdminControllerSetOrgLimitsData = {
    body: AdminSetLimitsDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/limits';
};

export type AdminControllerSetOrgLimitsResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerSetOrgLimitsResponse = AdminControllerSetOrgLimitsResponses[keyof AdminControllerSetOrgLimitsResponses];

export type AdminControllerSetOrgStatusData = {
    body: AdminSetStatusDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/status';
};

export type AdminControllerSetOrgStatusResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerSetOrgStatusResponse = AdminControllerSetOrgStatusResponses[keyof AdminControllerSetOrgStatusResponses];

export type AdminControllerSetOrgTrialData = {
    body: AdminSetTrialDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/trial';
};

export type AdminControllerSetOrgTrialResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerSetOrgTrialResponse = AdminControllerSetOrgTrialResponses[keyof AdminControllerSetOrgTrialResponses];

export type AdminControllerSetOrgBillingData = {
    body: AdminUpdateBillingDto;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/billing';
};

export type AdminControllerSetOrgBillingResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerSetOrgBillingResponse = AdminControllerSetOrgBillingResponses[keyof AdminControllerSetOrgBillingResponses];

export type AdminControllerDisableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/disable';
};

export type AdminControllerDisableOrgResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerDisableOrgResponse = AdminControllerDisableOrgResponses[keyof AdminControllerDisableOrgResponses];

export type AdminControllerEnableOrgData = {
    body?: never;
    path: {
        orgId: string;
    };
    query?: never;
    url: '/admin/orgs/{orgId}/enable';
};

export type AdminControllerEnableOrgResponses = {
    200: AdminOrgMutationResponseDto;
    201: AdminOrgMutationResponseDto;
};

export type AdminControllerEnableOrgResponse = AdminControllerEnableOrgResponses[keyof AdminControllerEnableOrgResponses];

export type AdminControllerGetUsersData = {
    body?: never;
    path?: never;
    query: {
        search: string;
        limit: string;
    };
    url: '/admin/users';
};

export type AdminControllerGetUsersResponses = {
    200: AdminUserListDto;
};

export type AdminControllerGetUsersResponse = AdminControllerGetUsersResponses[keyof AdminControllerGetUsersResponses];

export type AdminControllerDisableUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/disable';
};

export type AdminControllerDisableUserResponses = {
    200: AdminOkResponseDto;
    201: AdminOkResponseDto;
};

export type AdminControllerDisableUserResponse = AdminControllerDisableUserResponses[keyof AdminControllerDisableUserResponses];

export type AdminControllerEnableUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/enable';
};

export type AdminControllerEnableUserResponses = {
    200: AdminOkResponseDto;
    201: AdminOkResponseDto;
};

export type AdminControllerEnableUserResponse = AdminControllerEnableUserResponses[keyof AdminControllerEnableUserResponses];

export type AdminControllerListBillingEventsData = {
    body?: never;
    path?: never;
    query: {
        limit: string;
        orgId: string;
        eventName: string;
    };
    url: '/admin/billing-events';
};

export type AdminControllerListBillingEventsResponses = {
    200: AdminBillingEventListDto;
};

export type AdminControllerListBillingEventsResponse = AdminControllerListBillingEventsResponses[keyof AdminControllerListBillingEventsResponses];

export type AdminControllerReplayBillingEventData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/billing-events/{id}/replay';
};

export type AdminControllerReplayBillingEventResponses = {
    200: AdminBillingEventReplayResponseDto;
    201: AdminBillingEventReplayResponseDto;
};

export type AdminControllerReplayBillingEventResponse = AdminControllerReplayBillingEventResponses[keyof AdminControllerReplayBillingEventResponses];
