// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type Function = {
  [key: string]: unknown;
};

export type UserCreateDto = {
  email: string;
  username: string;
  first_name: string;
  last_name: string;
  password: string;
  action: "create" | "join";
  orgCreateProps?: Function;
  invitationCode?: string;
};

export type UserResponseDto = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  username: string;
  googleId: string | null;
  roles: Array<"user" | "admin" | "owner">;
  organizationId: string | null;
  deletedAt?: string | null;
};

export type SignInDto = {
  email: string;
  password: string;
};

export type AuthTokensResponseDto = {
  access_token: string;
  refresh_token: string;
};

export type GoogleAuthDto = {
  code?: string;
  idToken?: string;
};

export type GoogleAuthResponseDto = {
  access_token: string;
  refresh_token: string;
  needsOrg?: boolean;
};

export type CreateOrganizationDto = {
  name: string;
  slug: string;
  description?: string;
};

export type SetupOrgDto = {
  action: "create" | "join";
  orgCreateProps?: CreateOrganizationDto;
  invitationCode?: string;
};

export type RefreshTokenDto = {
  refresh_token: string;
};

export type IotCredentialsResponseDto = {
  endpoint: string;
  presignedWssUrl: string;
  expiresAt: string;
  /**
   * Org-scoped MQTT topic prefix. Subscribe topics must extend this with `/{envSlug}/{appId}/{channelId}/{eventType}/{agentId}` (use `+` for wildcards).
   */
  topicPrefix: string;
  /**
   * Default environment slug for this org. Frontends should slot this segment between `topicPrefix` and the appId when subscribing without an explicit env.
   */
  envSlug: string;
  /**
   * Human-readable template showing every topic segment the broker will publish to. Mirrors the publish-side topic-builder layout.
   */
  topicTemplate: string;
  clientId: string;
  region: string;
};

export type UpdateProfileDto = {
  first_name?: string;
  last_name?: string;
};

export type InvitationResponseDto = {
  id: string;
  invitationId: string;
  orgId: string;
  invitedEmail: string;
  role: string;
  inviteRole?: string;
  code?: string;
  status: string;
  expiresAt?: string;
  acceptedAt?: string;
  createdAt: string;
  updatedAt?: string;
};

export type EnvironmentResponseDto = {
  id: string;
  environmentId: string;
  orgId: string;
  name: string;
  slug: string;
  color?: string;
  isDefault?: boolean;
  isProduction?: boolean;
  isEphemeral?: boolean;
  expiresAt?: string;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
};

export type OrganizationResponseDto = {
  id: string;
  orgId: string;
  name: string;
  slug: string;
  description?: string;
  plan: string;
  ssoEnforced: boolean;
  eventsQuotaUsedCurrent: number;
  eventsQuotaMonthly?: number;
  retentionDays?: number;
  seatLimit?: number;
  lemonsqueezySubscriptionId?: string;
  lemonsqueezyCustomerId?: string;
  ssoConnectionId?: string;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
  invitations?: Array<InvitationResponseDto>;
  environments?: Array<EnvironmentResponseDto>;
};

export type UserOrganizationWithOrgResponseDto = {
  userId: string;
  orgId: string;
  role: string;
  joinedAt: string;
  deletedAt?: string;
  organization?: OrganizationResponseDto | null;
};

export type SwitchOrgDto = {
  organizationId: string;
};

export type SwitchActiveOrgResponseDto = {
  access_token: string;
  refresh_token: string;
  user?: UserResponseDto;
};

export type MessageResponseDto = {
  message: string;
};

export type OrganizationCreateResponseDto = {
  id: string;
  orgId: string;
  name: string;
  slug: string;
  description?: string;
  plan: string;
  ssoEnforced: boolean;
  eventsQuotaUsedCurrent: number;
  eventsQuotaMonthly?: number;
  retentionDays?: number;
  seatLimit?: number;
  lemonsqueezySubscriptionId?: string;
  lemonsqueezyCustomerId?: string;
  ssoConnectionId?: string;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
  invitations?: Array<InvitationResponseDto>;
  environments?: Array<EnvironmentResponseDto>;
  access_token: string;
  refresh_token: string;
};

export type OkResponseDto = {
  ok: boolean;
};

export type CreateInvitationDto = {
  invitedEmail: string;
  desired_role: "user" | "admin";
};

export type SuccessResponseDto = {
  success: boolean;
};

export type TransferOwnershipDto = {
  userId: string;
};

export type FeatureFlagsResponseDto = {
  billing: boolean;
  environments: boolean;
  sentryIngest: boolean;
  asyncIngest: boolean;
};

export type CreateEnvironmentDto = {
  name: string;
  slug?: string;
  color?: string;
  isProduction?: boolean;
  isDefault?: boolean;
  cloneFromEnvId?: string;
};

export type UpdateEnvironmentDto = {
  name?: string;
  color?: string;
  requireConfirmationForDestructive?: boolean;
};

export type CreateApiKeyDto = {
  name: string;
  organizationId: string;
  appId?: string;
  /**
   * Environment this key is bound to. All events published with this key will be tagged with this environment (unless allowEnvironmentOverride=true and the request specifies a different one).
   */
  environmentId?: string;
  /**
   * When true, the caller may override the env via X-Axonpush-Environment header or the event.environment field. Defaults to false for safety.
   */
  allowEnvironmentOverride?: boolean;
  scopes?: Array<
    | "publish"
    | "subscribe"
    | "events:read"
    | "traces:read"
    | "apps:manage"
    | "channels:manage"
    | "webhooks:manage"
  >;
};

export type ApiKeyCreateResponseDto = {
  id: string;
  apiKeyId: string;
  orgId: string;
  appId?: string;
  environmentId?: string;
  name: string;
  scopes: Array<
    | "publish"
    | "subscribe"
    | "events:read"
    | "traces:read"
    | "apps:manage"
    | "channels:manage"
    | "webhooks:manage"
  >;
  allowEnvironmentOverride: boolean;
  prefix?: string;
  lastUsedAt?: string;
  createdAt: string;
  updatedAt?: string;
  revokedAt?: string;
  /**
   * Raw API key, only returned at creation time
   */
  key: string;
};

export type ApiKeyResponseDto = {
  id: string;
  apiKeyId: string;
  orgId: string;
  appId?: string;
  environmentId?: string;
  name: string;
  scopes: Array<
    | "publish"
    | "subscribe"
    | "events:read"
    | "traces:read"
    | "apps:manage"
    | "channels:manage"
    | "webhooks:manage"
  >;
  allowEnvironmentOverride: boolean;
  prefix?: string;
  lastUsedAt?: string;
  createdAt: string;
  updatedAt?: string;
  revokedAt?: string;
};

export type CreatePublicTokenDto = {
  name: string;
  channelId: string;
  environmentId: string;
};

export type PublicIngestTokenCreateResponseDto = {
  id: string;
  tokenId: string;
  orgId: string;
  appId?: string;
  channelId?: string;
  environmentId?: string;
  name: string;
  scopes?: Array<string>;
  prefix?: string;
  lastUsedAt?: string;
  createdAt: string;
  revokedAt?: string;
  /**
   * Raw token, only returned at creation time
   */
  token: string;
};

export type PublicIngestTokenResponseDto = {
  id: string;
  tokenId: string;
  orgId: string;
  appId?: string;
  channelId?: string;
  environmentId?: string;
  name: string;
  scopes?: Array<string>;
  prefix?: string;
  lastUsedAt?: string;
  createdAt: string;
  revokedAt?: string;
};

export type ChannelResponseDto = {
  id: string;
  channelId: string;
  orgId: string;
  appId: string;
  name: string;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
  app?: AppResponseDto;
};

export type AppResponseDto = {
  id: string;
  appId: string;
  orgId: string;
  name: string;
  creatorUserId?: string;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
  channels: Array<Array<ChannelResponseDto>>;
};

export type CreateChannelDto = {
  name: string;
  appId: string;
};

export type CreateEventDto = {
  identifier: string;
  payload: {
    [key: string]: unknown;
  };
  channel_id: string;
  agentId?: string;
  traceId?: string;
  spanId?: string;
  parentEventId?: string;
  eventType?:
    | "agent.start"
    | "agent.end"
    | "agent.message"
    | "agent.tool_call.start"
    | "agent.tool_call.end"
    | "agent.error"
    | "agent.handoff"
    | "agent.llm.token"
    | "agent.log"
    | "app.log"
    | "app.span"
    | "custom";
  metadata?: {
    [key: string]: unknown;
  };
  /**
   * Environment slug override. Only honored when the API key has allowEnvironmentOverride=true.
   */
  environment?: string;
  /**
   * When true, wait for the event to be persisted to the DB before returning. Use only for audit-critical calls — the default async path returns in under a millisecond.
   */
  sync?: boolean;
};

export type EventIngestResponseDto = {
  eventId: string;
  identifier: string;
  dedupKey: string;
  createdAt: string;
  queued: boolean;
  duplicate?: boolean;
  environmentId?: string | null;
};

export type EventResponseDto = {
  id: string;
  eventId: string;
  orgId: string;
  appId: string;
  channelId: string;
  environmentId?: string;
  eventType: string;
  agentId?: string;
  traceId?: string;
  spanId?: string;
  parentEventId?: string;
  identifier?: string;
  payload?: {
    [key: string]: unknown;
  };
  metadata?: {
    [key: string]: unknown;
  };
  createdAt: string;
  updatedAt?: string;
  ttl?: number;
};

export type EventListMetaDto = {
  hasMore: boolean;
  cursor?: string | null;
};

export type EventListResponseDto = {
  data: Array<EventResponseDto>;
  meta: EventListMetaDto;
};

export type CreateAppDto = {
  name: string;
};

export type CreateWebhookEndpointDto = {
  url: string;
  channelId: string;
  secret?: string;
  /**
   * Event types to filter (null = all)
   */
  eventTypes?: Array<string>;
  description?: string;
};

export type WebhookEndpointCreateResponseDto = {
  id: string;
  endpointId: string;
  orgId?: string;
  channelId: string;
  url: string;
  eventTypes?: Array<string>;
  signingSecretPrefix?: string;
  hasSecret?: boolean;
  description?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
  /**
   * Raw signing secret, only returned at creation time
   */
  rawSecret?: string;
  /**
   * Prefix of the signing secret
   */
  secretPrefix?: string | null;
};

export type WebhookEndpointResponseDto = {
  id: string;
  endpointId: string;
  orgId?: string;
  channelId: string;
  url: string;
  eventTypes?: Array<string>;
  signingSecretPrefix?: string;
  hasSecret?: boolean;
  description?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt?: string;
  deletedAt?: string;
};

export type WebhookDeliveryResponseDto = {
  id: string;
  deliveryId: string;
  endpointId: string;
  eventId: string;
  status: "pending" | "success" | "failed" | "retrying";
  statusCode?: number;
  responseBody?: string;
  attempts: number;
  lastAttemptAt?: string;
  nextAttemptAt?: string;
  error?: string;
  createdAt: string;
};

export type WebhookIngestResponseDto = {
  status: string;
  eventId: string;
};

export type AuditLogActorDto = {
  id: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  username?: string;
};

export type AuditLogResponseDto = {
  id: string;
  auditId: string;
  organizationId?: string;
  orgId?: string;
  actorId?: string | null;
  action: string;
  resourceType: string;
  resourceId?: string;
  metadata?: {
    [key: string]: unknown;
  } | null;
  ipAddress?: string | null;
  actor?: AuditLogActorDto | null;
  createdAt: string;
};

export type AuditLogListMetaDto = {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};

export type AuditLogListResponseDto = {
  data: Array<AuditLogResponseDto>;
  meta: AuditLogListMetaDto;
};

export type HealthResponseDto = {
  status: string;
  timestamp: string;
  flags: {
    [key: string]: unknown;
  };
};

export type CreateReleaseDto = {
  version: string;
  projects?: Array<string>;
  dateReleased?: string;
};

export type ReleaseResponseDto = {
  orgId: string;
  version: string;
  projects?: string;
  dateCreated: string;
  dateReleased?: string;
  firstEventAt?: string;
  lastEventAt?: string;
};

export type ReleaseArtifactResponseDto = {
  orgId: string;
  version: string;
  artifactId: string;
  name: string;
  contentType?: string;
  sizeBytes: number;
  storagePath: string;
  sha256?: string;
  createdAt: string;
};

export type SsoConnectionResponseDto = {
  clientID: string;
  tenant?: string;
  product?: string;
  defaultRedirectUrl?: string;
  redirectUrl?: Array<string>;
};

export type ToggleEnforcementDto = {
  enforced: boolean;
};

export type SsoEnforcementResponseDto = {
  ok: boolean;
  enforced: boolean;
};

export type SsoAuthorizeResponseDto = {
  redirect_url: string;
};

export type SsoCallbackDto = {
  code: string;
};

export type AppControllerGetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type AppControllerGetHelloResponses = {
  200: string;
};

export type AppControllerGetHelloResponse =
  AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AuthControllerSignUpData = {
  body: UserCreateDto;
  path?: never;
  query?: never;
  url: "/auth/signup";
};

export type AuthControllerSignUpResponses = {
  201: UserResponseDto;
};

export type AuthControllerSignUpResponse =
  AuthControllerSignUpResponses[keyof AuthControllerSignUpResponses];

export type AuthControllerSignInData = {
  body: SignInDto;
  path?: never;
  query?: never;
  url: "/auth/signin";
};

export type AuthControllerSignInResponses = {
  200: AuthTokensResponseDto;
  201: unknown;
};

export type AuthControllerSignInResponse =
  AuthControllerSignInResponses[keyof AuthControllerSignInResponses];

export type AuthControllerGoogleAuthData = {
  body: GoogleAuthDto;
  path?: never;
  query?: never;
  url: "/auth/google";
};

export type AuthControllerGoogleAuthResponses = {
  200: GoogleAuthResponseDto;
  201: {
    [key: string]: unknown;
  };
};

export type AuthControllerGoogleAuthResponse =
  AuthControllerGoogleAuthResponses[keyof AuthControllerGoogleAuthResponses];

export type AuthControllerSetupOrgData = {
  body: SetupOrgDto;
  path?: never;
  query?: never;
  url: "/auth/setup-org";
};

export type AuthControllerSetupOrgResponses = {
  200: AuthTokensResponseDto;
  201: unknown;
};

export type AuthControllerSetupOrgResponse =
  AuthControllerSetupOrgResponses[keyof AuthControllerSetupOrgResponses];

export type AuthControllerRefreshData = {
  body: RefreshTokenDto;
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type AuthControllerRefreshResponses = {
  200: AuthTokensResponseDto;
  201: unknown;
};

export type AuthControllerRefreshResponse =
  AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type IotCredentialsControllerGetCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/iot-credentials";
};

export type IotCredentialsControllerGetCredentialsResponses = {
  200: IotCredentialsResponseDto;
};

export type IotCredentialsControllerGetCredentialsResponse =
  IotCredentialsControllerGetCredentialsResponses[keyof IotCredentialsControllerGetCredentialsResponses];

export type UserControllerGetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UserControllerGetMeResponses = {
  200: UserResponseDto;
};

export type UserControllerGetMeResponse =
  UserControllerGetMeResponses[keyof UserControllerGetMeResponses];

export type UserControllerUpdateMeData = {
  body: UpdateProfileDto;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UserControllerUpdateMeResponses = {
  200: UserResponseDto;
};

export type UserControllerUpdateMeResponse =
  UserControllerUpdateMeResponses[keyof UserControllerUpdateMeResponses];

export type UserControllerGetMyOrganizationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/organizations";
};

export type UserControllerGetMyOrganizationsResponses = {
  200: Array<UserOrganizationWithOrgResponseDto>;
};

export type UserControllerGetMyOrganizationsResponse =
  UserControllerGetMyOrganizationsResponses[keyof UserControllerGetMyOrganizationsResponses];

export type UserControllerSwitchActiveOrgData = {
  body: SwitchOrgDto;
  path?: never;
  query?: never;
  url: "/users/me/active-org";
};

export type UserControllerSwitchActiveOrgResponses = {
  200: SwitchActiveOrgResponseDto;
};

export type UserControllerSwitchActiveOrgResponse =
  UserControllerSwitchActiveOrgResponses[keyof UserControllerSwitchActiveOrgResponses];

export type UserControllerGetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users";
};

export type UserControllerGetUsersResponses = {
  200: Array<UserResponseDto>;
};

export type UserControllerGetUsersResponse =
  UserControllerGetUsersResponses[keyof UserControllerGetUsersResponses];

export type UserControllerDeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerDeleteUserResponses = {
  200: MessageResponseDto;
};

export type UserControllerDeleteUserResponse =
  UserControllerDeleteUserResponses[keyof UserControllerDeleteUserResponses];

export type UserControllerUpdateUserData = {
  body: UpdateProfileDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UserControllerUpdateUserResponses = {
  200: UserResponseDto;
};

export type UserControllerUpdateUserResponse =
  UserControllerUpdateUserResponses[keyof UserControllerUpdateUserResponses];

export type OrganizationControllerGetAllOrganizationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/organizations";
};

export type OrganizationControllerGetAllOrganizationsResponses = {
  200: Array<OrganizationResponseDto>;
};

export type OrganizationControllerGetAllOrganizationsResponse =
  OrganizationControllerGetAllOrganizationsResponses[keyof OrganizationControllerGetAllOrganizationsResponses];

export type OrganizationControllerCreateOrganizationData = {
  body: CreateOrganizationDto;
  path?: never;
  query?: never;
  url: "/organizations";
};

export type OrganizationControllerCreateOrganizationResponses = {
  201: OrganizationCreateResponseDto;
};

export type OrganizationControllerCreateOrganizationResponse =
  OrganizationControllerCreateOrganizationResponses[keyof OrganizationControllerCreateOrganizationResponses];

export type OrganizationControllerDeleteOrganizationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/organizations/{id}";
};

export type OrganizationControllerDeleteOrganizationResponses = {
  200: OkResponseDto;
};

export type OrganizationControllerDeleteOrganizationResponse =
  OrganizationControllerDeleteOrganizationResponses[keyof OrganizationControllerDeleteOrganizationResponses];

export type OrganizationControllerGetOrganizationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/organizations/{id}";
};

export type OrganizationControllerGetOrganizationResponses = {
  200: OrganizationResponseDto;
};

export type OrganizationControllerGetOrganizationResponse =
  OrganizationControllerGetOrganizationResponses[keyof OrganizationControllerGetOrganizationResponses];

export type OrganizationControllerEditOrganizationData = {
  body: CreateOrganizationDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/organizations/{id}";
};

export type OrganizationControllerEditOrganizationResponses = {
  200: OkResponseDto;
};

export type OrganizationControllerEditOrganizationResponse =
  OrganizationControllerEditOrganizationResponses[keyof OrganizationControllerEditOrganizationResponses];

export type OrganizationControllerCreateInvitationData = {
  body: CreateInvitationDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/organizations/{id}/invitations";
};

export type OrganizationControllerCreateInvitationResponses = {
  201: InvitationResponseDto;
};

export type OrganizationControllerCreateInvitationResponse =
  OrganizationControllerCreateInvitationResponses[keyof OrganizationControllerCreateInvitationResponses];

export type OrganizationControllerRemoveMemberData = {
  body?: never;
  path: {
    id: string;
    userId: string;
  };
  query?: never;
  url: "/organizations/{id}/members/{userId}";
};

export type OrganizationControllerRemoveMemberResponses = {
  200: SuccessResponseDto;
};

export type OrganizationControllerRemoveMemberResponse =
  OrganizationControllerRemoveMemberResponses[keyof OrganizationControllerRemoveMemberResponses];

export type OrganizationControllerTransferOwnershipData = {
  body: TransferOwnershipDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/organizations/{id}/transfer-ownership";
};

export type OrganizationControllerTransferOwnershipResponses = {
  200: SuccessResponseDto;
  201: unknown;
};

export type OrganizationControllerTransferOwnershipResponse =
  OrganizationControllerTransferOwnershipResponses[keyof OrganizationControllerTransferOwnershipResponses];

export type OrganizationControllerDeleteInvitationData = {
  body?: never;
  path: {
    id: string;
    invitationId: string;
  };
  query?: never;
  url: "/organizations/{id}/invitations/{invitationId}";
};

export type OrganizationControllerDeleteInvitationResponses = {
  200: SuccessResponseDto;
};

export type OrganizationControllerDeleteInvitationResponse =
  OrganizationControllerDeleteInvitationResponses[keyof OrganizationControllerDeleteInvitationResponses];

export type FeatureFlagsControllerMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/feature-flags/me";
};

export type FeatureFlagsControllerMeResponses = {
  200: FeatureFlagsResponseDto;
};

export type FeatureFlagsControllerMeResponse =
  FeatureFlagsControllerMeResponses[keyof FeatureFlagsControllerMeResponses];

export type EnvironmentControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/environments";
};

export type EnvironmentControllerListResponses = {
  200: Array<EnvironmentResponseDto>;
};

export type EnvironmentControllerListResponse =
  EnvironmentControllerListResponses[keyof EnvironmentControllerListResponses];

export type EnvironmentControllerCreateData = {
  body: CreateEnvironmentDto;
  path?: never;
  query?: never;
  url: "/environments";
};

export type EnvironmentControllerCreateResponses = {
  201: EnvironmentResponseDto;
};

export type EnvironmentControllerCreateResponse =
  EnvironmentControllerCreateResponses[keyof EnvironmentControllerCreateResponses];

export type EnvironmentControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/environments/{id}";
};

export type EnvironmentControllerRemoveResponses = {
  200: OkResponseDto;
};

export type EnvironmentControllerRemoveResponse =
  EnvironmentControllerRemoveResponses[keyof EnvironmentControllerRemoveResponses];

export type EnvironmentControllerUpdateData = {
  body: UpdateEnvironmentDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/environments/{id}";
};

export type EnvironmentControllerUpdateResponses = {
  200: EnvironmentResponseDto;
};

export type EnvironmentControllerUpdateResponse =
  EnvironmentControllerUpdateResponses[keyof EnvironmentControllerUpdateResponses];

export type EnvironmentControllerPromoteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/environments/{id}/promote-to-default";
};

export type EnvironmentControllerPromoteResponses = {
  200: EnvironmentResponseDto;
  201: {
    [key: string]: unknown;
  };
};

export type EnvironmentControllerPromoteResponse =
  EnvironmentControllerPromoteResponses[keyof EnvironmentControllerPromoteResponses];

export type ApiKeyControllerListApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type ApiKeyControllerListApiKeysResponses = {
  200: Array<ApiKeyResponseDto>;
};

export type ApiKeyControllerListApiKeysResponse =
  ApiKeyControllerListApiKeysResponses[keyof ApiKeyControllerListApiKeysResponses];

export type ApiKeyControllerCreateApiKeyData = {
  body: CreateApiKeyDto;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type ApiKeyControllerCreateApiKeyResponses = {
  201: ApiKeyCreateResponseDto;
};

export type ApiKeyControllerCreateApiKeyResponse =
  ApiKeyControllerCreateApiKeyResponses[keyof ApiKeyControllerCreateApiKeyResponses];

export type ApiKeyControllerRevokeApiKeyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api-keys/{id}";
};

export type ApiKeyControllerRevokeApiKeyResponses = {
  200: MessageResponseDto;
};

export type ApiKeyControllerRevokeApiKeyResponse =
  ApiKeyControllerRevokeApiKeyResponses[keyof ApiKeyControllerRevokeApiKeyResponses];

export type PublicIngestTokenControllerListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public-tokens";
};

export type PublicIngestTokenControllerListResponses = {
  200: Array<PublicIngestTokenResponseDto>;
};

export type PublicIngestTokenControllerListResponse =
  PublicIngestTokenControllerListResponses[keyof PublicIngestTokenControllerListResponses];

export type PublicIngestTokenControllerCreateData = {
  body: CreatePublicTokenDto;
  path?: never;
  query?: never;
  url: "/public-tokens";
};

export type PublicIngestTokenControllerCreateResponses = {
  201: PublicIngestTokenCreateResponseDto;
};

export type PublicIngestTokenControllerCreateResponse =
  PublicIngestTokenControllerCreateResponses[keyof PublicIngestTokenControllerCreateResponses];

export type PublicIngestTokenControllerRevokeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/public-tokens/{id}";
};

export type PublicIngestTokenControllerRevokeResponses = {
  200: OkResponseDto;
};

export type PublicIngestTokenControllerRevokeResponse =
  PublicIngestTokenControllerRevokeResponses[keyof PublicIngestTokenControllerRevokeResponses];

export type ChannelControllerDeleteChannelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/channel/{id}";
};

export type ChannelControllerDeleteChannelResponses = {
  200: OkResponseDto;
};

export type ChannelControllerDeleteChannelResponse =
  ChannelControllerDeleteChannelResponses[keyof ChannelControllerDeleteChannelResponses];

export type ChannelControllerGetChannelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/channel/{id}";
};

export type ChannelControllerGetChannelResponses = {
  200: ChannelResponseDto;
};

export type ChannelControllerGetChannelResponse =
  ChannelControllerGetChannelResponses[keyof ChannelControllerGetChannelResponses];

export type ChannelControllerUpdateChannelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/channel/{id}";
};

export type ChannelControllerUpdateChannelResponses = {
  200: OkResponseDto;
};

export type ChannelControllerUpdateChannelResponse =
  ChannelControllerUpdateChannelResponses[keyof ChannelControllerUpdateChannelResponses];

export type ChannelControllerCreateChannelData = {
  body: CreateChannelDto;
  path?: never;
  query?: never;
  url: "/channel";
};

export type ChannelControllerCreateChannelResponses = {
  201: ChannelResponseDto;
};

export type ChannelControllerCreateChannelResponse =
  ChannelControllerCreateChannelResponses[keyof ChannelControllerCreateChannelResponses];

export type EventControllerCreateEventData = {
  body: CreateEventDto;
  headers?: {
    /**
     * Stripe-style client-supplied idempotency key (1–255 ASCII-printable chars). Cached response replay for retried requests.
     */
    "Idempotency-Key"?: string;
  };
  path?: never;
  query?: never;
  url: "/event";
};

export type EventControllerCreateEventResponses = {
  201: EventIngestResponseDto;
};

export type EventControllerCreateEventResponse =
  EventControllerCreateEventResponses[keyof EventControllerCreateEventResponses];

export type EventControllerListEventsData = {
  body?: never;
  path: {
    channelId: string;
  };
  query?: {
    payloadFilter?: string;
    /**
     * Page size, 1-1000. Defaults to 100.
     */
    limit?: number;
    cursor?: string;
    /**
     * ISO 8601 datetime (exclusive upper bound).
     */
    until?: string;
    /**
     * ISO 8601 datetime (inclusive lower bound).
     */
    since?: string;
    traceId?: string;
    agentId?: string;
    eventType?: Array<string>;
    /**
     * Environment slug. Resolved server-side to environmentId.
     */
    environment?: string;
  };
  url: "/event/{channelId}/list";
};

export type EventControllerListEventsResponses = {
  200: EventListResponseDto;
};

export type EventControllerListEventsResponse =
  EventControllerListEventsResponses[keyof EventControllerListEventsResponses];

export type EventsSearchControllerSearchData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by ingest source (e.g. "app", "sentry", "otlp").
     */
    source?: string;
    /**
     * JSON-path / dotted filter applied to the event payload.
     */
    payloadFilter?: string;
    /**
     * Page size, 1-1000. Defaults to 100.
     */
    limit?: number;
    /**
     * Opaque pagination cursor returned by a previous call.
     */
    cursor?: string;
    /**
     * ISO 8601 datetime (exclusive upper bound).
     */
    until?: string;
    /**
     * ISO 8601 datetime (inclusive lower bound).
     */
    since?: string;
    traceId?: string;
    agentId?: string;
    /**
     * Repeat or comma-separate to filter by multiple event types.
     */
    eventType?: Array<string>;
    channelId?: string;
    appId?: string;
    /**
     * Environment slug. Resolved server-side to environmentId.
     */
    environment?: string;
  };
  url: "/events/search";
};

export type EventsSearchControllerSearchResponses = {
  200: EventListResponseDto;
};

export type EventsSearchControllerSearchResponse =
  EventsSearchControllerSearchResponses[keyof EventsSearchControllerSearchResponses];

export type AppsControllerGetAllAppsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsControllerGetAllAppsResponses = {
  200: Array<AppResponseDto>;
};

export type AppsControllerGetAllAppsResponse =
  AppsControllerGetAllAppsResponses[keyof AppsControllerGetAllAppsResponses];

export type AppsControllerCreateAppData = {
  body: CreateAppDto;
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsControllerCreateAppResponses = {
  201: AppResponseDto;
};

export type AppsControllerCreateAppResponse =
  AppsControllerCreateAppResponses[keyof AppsControllerCreateAppResponses];

export type AppsControllerDeleteAppData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/apps/{id}";
};

export type AppsControllerDeleteAppResponses = {
  200: OkResponseDto;
};

export type AppsControllerDeleteAppResponse =
  AppsControllerDeleteAppResponses[keyof AppsControllerDeleteAppResponses];

export type AppsControllerGetAppData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/apps/{id}";
};

export type AppsControllerGetAppResponses = {
  200: AppResponseDto;
};

export type AppsControllerGetAppResponse =
  AppsControllerGetAppResponses[keyof AppsControllerGetAppResponses];

export type AppsControllerEditAppData = {
  body: CreateAppDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/apps/{id}";
};

export type AppsControllerEditAppResponses = {
  200: OkResponseDto;
};

export type AppsControllerEditAppResponse =
  AppsControllerEditAppResponses[keyof AppsControllerEditAppResponses];

export type WebhookControllerCreateEndpointData = {
  body: CreateWebhookEndpointDto;
  path?: never;
  query?: never;
  url: "/webhooks/endpoints";
};

export type WebhookControllerCreateEndpointResponses = {
  201: WebhookEndpointCreateResponseDto;
};

export type WebhookControllerCreateEndpointResponse =
  WebhookControllerCreateEndpointResponses[keyof WebhookControllerCreateEndpointResponses];

export type WebhookControllerListEndpointsData = {
  body?: never;
  path: {
    channelId: string;
  };
  query?: never;
  url: "/webhooks/endpoints/channel/{channelId}";
};

export type WebhookControllerListEndpointsResponses = {
  200: Array<WebhookEndpointResponseDto>;
};

export type WebhookControllerListEndpointsResponse =
  WebhookControllerListEndpointsResponses[keyof WebhookControllerListEndpointsResponses];

export type WebhookControllerDeleteEndpointData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/webhooks/endpoints/{id}";
};

export type WebhookControllerDeleteEndpointResponses = {
  200: MessageResponseDto;
};

export type WebhookControllerDeleteEndpointResponse =
  WebhookControllerDeleteEndpointResponses[keyof WebhookControllerDeleteEndpointResponses];

export type WebhookControllerGetDeliveriesData = {
  body?: never;
  path: {
    endpointId: string;
  };
  query?: never;
  url: "/webhooks/deliveries/{endpointId}";
};

export type WebhookControllerGetDeliveriesResponses = {
  200: Array<WebhookDeliveryResponseDto>;
};

export type WebhookControllerGetDeliveriesResponse =
  WebhookControllerGetDeliveriesResponses[keyof WebhookControllerGetDeliveriesResponses];

export type WebhookControllerIngestWebhookData = {
  body?: never;
  headers: {
    "X-Webhook-Signature": string;
  };
  path: {
    endpointId: string;
  };
  query?: never;
  url: "/webhooks/ingest/{endpointId}";
};

export type WebhookControllerIngestWebhookResponses = {
  201: WebhookIngestResponseDto;
};

export type WebhookControllerIngestWebhookResponse =
  WebhookControllerIngestWebhookResponses[keyof WebhookControllerIngestWebhookResponses];

export type TraceControllerListTracesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    appId?: string;
    environment?: string;
  };
  url: "/traces";
};

export type TraceControllerListTracesResponses = {
  /**
   * Paginated list of trace summaries
   */
  200: {
    data: Array<{
      traceId: string;
      eventCount: number;
      agents: Array<string>;
      eventTypes: Array<string>;
      startTime: string;
      endTime: string;
      duration: number;
      errorCount: number;
      toolCallCount: number;
      handoffCount: number;
    }>;
    meta: {
      page: number;
      limit: number;
      hasMore: boolean;
    };
  };
};

export type TraceControllerListTracesResponse =
  TraceControllerListTracesResponses[keyof TraceControllerListTracesResponses];

export type TraceControllerGetDashboardStatsData = {
  body?: never;
  path?: never;
  query?: {
    appId?: string;
    environment?: string;
  };
  url: "/traces/stats";
};

export type TraceControllerGetDashboardStatsResponses = {
  /**
   * Aggregated dashboard stats for the caller organization
   */
  200: {
    totalEvents: number;
    eventsToday: number;
    totalTraces: number;
    tracesToday: number;
    errorCount: number;
    errorRate: number;
    avgTraceDuration: number;
    eventsByHour: Array<{
      hour?: string;
      count?: number;
    }>;
  };
};

export type TraceControllerGetDashboardStatsResponse =
  TraceControllerGetDashboardStatsResponses[keyof TraceControllerGetDashboardStatsResponses];

export type TraceControllerGetTraceEventsData = {
  body?: never;
  path: {
    traceId: string;
  };
  query?: {
    appId?: string;
    environment?: string;
  };
  url: "/traces/{traceId}/events";
};

export type TraceControllerGetTraceEventsResponses = {
  /**
   * All events belonging to a trace, ordered by createdAt ASC
   */
  200: Array<EventResponseDto>;
};

export type TraceControllerGetTraceEventsResponse =
  TraceControllerGetTraceEventsResponses[keyof TraceControllerGetTraceEventsResponses];

export type TraceControllerGetTraceSummaryData = {
  body?: never;
  path: {
    traceId: string;
  };
  query?: {
    appId?: string;
    environment?: string;
  };
  url: "/traces/{traceId}/summary";
};

export type TraceControllerGetTraceSummaryResponses = {
  /**
   * Aggregated summary for a single trace
   */
  200: {
    traceId: string;
    eventCount: number;
    agents: Array<string>;
    eventTypes: Array<string>;
    startTime: string;
    endTime: string;
    duration: number;
    errorCount: number;
    toolCallCount: number;
    handoffCount: number;
  };
};

export type TraceControllerGetTraceSummaryResponse =
  TraceControllerGetTraceSummaryResponses[keyof TraceControllerGetTraceSummaryResponses];

export type AuditLogControllerListAuditLogsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    action?: string;
    resourceType?: string;
    actorId?: string;
    from?: string;
    to?: string;
  };
  url: "/audit-logs";
};

export type AuditLogControllerListAuditLogsResponses = {
  /**
   * Paginated list of audit log entries for the caller organization
   */
  200: AuditLogListResponseDto;
};

export type AuditLogControllerListAuditLogsResponse =
  AuditLogControllerListAuditLogsResponses[keyof AuditLogControllerListAuditLogsResponses];

export type OtlpControllerIngestLogsData = {
  body?: never;
  headers: {
    "X-Axonpush-Channel": string;
    "Idempotency-Key"?: string;
    "X-Axonpush-Environment"?: string;
  };
  path?: never;
  query?: never;
  url: "/v1/logs";
};

export type OtlpControllerIngestLogsResponses = {
  200: unknown;
  201: {
    [key: string]: unknown;
  };
};

export type OtlpControllerIngestLogsResponse =
  OtlpControllerIngestLogsResponses[keyof OtlpControllerIngestLogsResponses];

export type OtlpControllerIngestTracesData = {
  body?: never;
  headers: {
    "X-Axonpush-Channel": string;
    "Idempotency-Key"?: string;
    "X-Axonpush-Environment"?: string;
  };
  path?: never;
  query?: never;
  url: "/v1/traces";
};

export type OtlpControllerIngestTracesResponses = {
  200: unknown;
  201: {
    [key: string]: unknown;
  };
};

export type OtlpControllerIngestTracesResponse =
  OtlpControllerIngestTracesResponses[keyof OtlpControllerIngestTracesResponses];

export type HealthControllerCheckData = {
  body?: never;
  path?: never;
  query?: {
    deep?: boolean;
  };
  url: "/health";
};

export type HealthControllerCheckResponses = {
  200: HealthResponseDto;
};

export type HealthControllerCheckResponse =
  HealthControllerCheckResponses[keyof HealthControllerCheckResponses];

export type ReleaseControllerListData = {
  body?: never;
  path: {
    orgId: string;
  };
  query?: never;
  url: "/organizations/{orgId}/releases";
};

export type ReleaseControllerListResponses = {
  200: Array<ReleaseResponseDto>;
};

export type ReleaseControllerListResponse =
  ReleaseControllerListResponses[keyof ReleaseControllerListResponses];

export type ReleaseControllerCreateData = {
  body: CreateReleaseDto;
  path: {
    orgId: string;
  };
  query?: never;
  url: "/organizations/{orgId}/releases";
};

export type ReleaseControllerCreateResponses = {
  201: ReleaseResponseDto;
};

export type ReleaseControllerCreateResponse =
  ReleaseControllerCreateResponses[keyof ReleaseControllerCreateResponses];

export type ReleaseControllerUploadArtifactData = {
  body?: never;
  path: {
    version: string;
  };
  query?: never;
  url: "/releases/{version}/artifacts";
};

export type ReleaseControllerUploadArtifactResponses = {
  201: ReleaseArtifactResponseDto;
};

export type ReleaseControllerUploadArtifactResponse =
  ReleaseControllerUploadArtifactResponses[keyof ReleaseControllerUploadArtifactResponses];

export type SentryControllerIngestEnvelopeData = {
  body?: never;
  path: {
    projectId: string;
  };
  query?: never;
  url: "/api/{projectId}/envelope";
};

export type SentryControllerIngestEnvelopeResponses = {
  201: unknown;
};

export type SentryControllerIngestStoreData = {
  body?: never;
  path: {
    projectId: string;
  };
  query?: never;
  url: "/api/{projectId}/store";
};

export type SentryControllerIngestStoreResponses = {
  201: unknown;
};

export type SentryControllerIngestSecurityData = {
  body?: never;
  path: {
    projectId: string;
  };
  query?: never;
  url: "/api/{projectId}/security";
};

export type SentryControllerIngestSecurityResponses = {
  201: unknown;
};

export type SentryControllerIngestMinidumpData = {
  body?: never;
  path: {
    projectId: string;
  };
  query?: never;
  url: "/api/{projectId}/minidump";
};

export type SentryControllerIngestMinidumpResponses = {
  201: unknown;
};

export type SsoControllerGetConnectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sso/connections";
};

export type SsoControllerGetConnectionsResponses = {
  200: Array<SsoConnectionResponseDto>;
};

export type SsoControllerGetConnectionsResponse =
  SsoControllerGetConnectionsResponses[keyof SsoControllerGetConnectionsResponses];

export type SsoControllerCreateConnectionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/sso/connections";
};

export type SsoControllerCreateConnectionResponses = {
  201: SsoConnectionResponseDto;
};

export type SsoControllerCreateConnectionResponse =
  SsoControllerCreateConnectionResponses[keyof SsoControllerCreateConnectionResponses];

export type SsoControllerDeleteConnectionData = {
  body?: never;
  path: {
    clientID: string;
  };
  query?: never;
  url: "/sso/connections/{clientID}";
};

export type SsoControllerDeleteConnectionResponses = {
  200: OkResponseDto;
};

export type SsoControllerDeleteConnectionResponse =
  SsoControllerDeleteConnectionResponses[keyof SsoControllerDeleteConnectionResponses];

export type SsoControllerToggleEnforcementData = {
  body: ToggleEnforcementDto;
  path?: never;
  query?: never;
  url: "/sso/enforcement";
};

export type SsoControllerToggleEnforcementResponses = {
  200: SsoEnforcementResponseDto;
};

export type SsoControllerToggleEnforcementResponse =
  SsoControllerToggleEnforcementResponses[keyof SsoControllerToggleEnforcementResponses];

export type SsoControllerAuthorizeData = {
  body?: never;
  path?: never;
  query?: {
    email?: string;
    org_slug?: string;
  };
  url: "/auth/sso/authorize";
};

export type SsoControllerAuthorizeResponses = {
  200: SsoAuthorizeResponseDto;
};

export type SsoControllerAuthorizeResponse =
  SsoControllerAuthorizeResponses[keyof SsoControllerAuthorizeResponses];

export type SsoControllerCallbackData = {
  body: SsoCallbackDto;
  path?: never;
  query?: never;
  url: "/auth/sso/callback";
};

export type SsoControllerCallbackResponses = {
  201: AuthTokensResponseDto;
};

export type SsoControllerCallbackResponse =
  SsoControllerCallbackResponses[keyof SsoControllerCallbackResponses];

export type SsoControllerSamlAcsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/sso/acs";
};

export type SsoControllerSamlAcsResponses = {
  201: unknown;
};
