/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_googleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_setupOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_updateMe"];
        trace?: never;
    };
    "/users/me/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMyOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/active-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_switchActiveOrg"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UserController_updateUser"];
        post?: never;
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationController_getAllOrganizations"];
        put?: never;
        post: operations["OrganizationController_createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationController_getOrganization"];
        put?: never;
        post?: never;
        delete: operations["OrganizationController_deleteOrganization"];
        options?: never;
        head?: never;
        patch: operations["OrganizationController_editOrganization"];
        trace?: never;
    };
    "/organizations/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationController_createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganizationController_deleteInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApiKeyController_listApiKeys"];
        put?: never;
        post: operations["ApiKeyController_createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ApiKeyController_revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppsController_getAllApps"];
        put?: never;
        post: operations["AppsController_createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppsController_getApp"];
        put?: never;
        post?: never;
        delete: operations["AppsController_deleteApp"];
        options?: never;
        head?: never;
        patch: operations["AppsController_editApp"];
        trace?: never;
    };
    "/channel/{channelId}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChannelController_subscribeToChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/{channelId}/{eventIdentifier}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChannelController_subscribeToEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChannelController_getChannel"];
        put: operations["ChannelController_updateChannel"];
        post?: never;
        delete: operations["ChannelController_deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChannelController_createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{channelId}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventController_listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsSearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebhookController_createEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/endpoints/channel/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WebhookController_listEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WebhookController_deleteEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/deliveries/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WebhookController_getDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/ingest/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebhookController_ingestWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{traceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getTraceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{traceId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getTraceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditLogController_listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP/HTTP/JSON logs ingest
         * @description OpenTelemetry-compatible log ingest endpoint. Accepts an OTLP LogsExportRequest envelope and stores each LogRecord as an `app.log` event row in the channel identified by the X-Axonpush-Channel header.
         */
        post: operations["OtlpController_ingestLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP/HTTP/JSON traces ingest
         * @description OpenTelemetry-compatible trace ingest endpoint. Accepts an OTLP TracesExportRequest envelope and stores each Span as an `app.span` event row in the channel identified by the X-Axonpush-Channel header.
         */
        post: operations["OtlpController_ingestTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrganizationDto: {
            name: string;
            slug: string;
            description?: string;
        };
        UserCreateDto: {
            email: string;
            username: string;
            first_name: string;
            last_name: string;
            password: string;
            /** @enum {string} */
            action: "create" | "join";
            orgCreateProps?: components["schemas"]["CreateOrganizationDto"];
            invitationCode?: string;
        };
        SignInDto: {
            email: string;
            password: string;
        };
        GoogleAuthDto: {
            code?: string;
            idToken?: string;
        };
        SetupOrgDto: {
            /** @enum {string} */
            action: "create" | "join";
            orgCreateProps?: components["schemas"]["CreateOrganizationDto"];
            invitationCode?: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        UserResponseDto: {
            id: number;
            first_name: string;
            last_name: string;
            email: string;
            username: string;
            googleId: string | null;
            roles: ("user" | "admin")[];
            organizationId: number;
            /** Format: date-time */
            deletedAt?: string | null;
        };
        UpdateProfileDto: {
            first_name?: string;
            last_name?: string;
        };
        Event: {
            id: number;
            identifier: string;
            payload: Record<string, never>;
            agentId: string;
            traceId: string;
            spanId: string;
            parentEventId: number;
            /** @enum {string} */
            eventType: "agent.start" | "agent.end" | "agent.message" | "agent.tool_call.start" | "agent.tool_call.end" | "agent.error" | "agent.handoff" | "agent.llm.token" | "agent.log" | "app.log" | "app.span" | "custom";
            metadata: Record<string, never>;
            channel: components["schemas"]["Channel"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Channel: {
            id: number;
            name: string;
            app: components["schemas"]["App"];
            events: components["schemas"]["Event"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        App: {
            id: number;
            name: string;
            creator: components["schemas"]["User"];
            organization: components["schemas"]["Organization"];
            organizationId: number;
            channels: components["schemas"]["Channel"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        Invitation: {
            id: number;
            code: string;
            invitedEmail: string;
            /** @enum {string} */
            invite_role: "user" | "admin";
            /** @enum {string} */
            status: "pending" | "accepted" | "expired";
            organization: components["schemas"]["Organization"];
            organizationId: number;
        };
        UserOrganization: {
            id: number;
            user: components["schemas"]["User"];
            userId: number;
            organization: components["schemas"]["Organization"];
            organizationId: number;
            /** @enum {string} */
            role: "user" | "admin";
            /** Format: date-time */
            joinedAt: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        Organization: {
            id: number;
            slug: string;
            name: string;
            description: string;
            users: components["schemas"]["User"][];
            apps: components["schemas"]["App"][];
            invitations: components["schemas"]["Invitation"][];
            memberships: components["schemas"]["UserOrganization"][];
            /** Format: date-time */
            deletedAt?: string;
        };
        User: {
            id: number;
            first_name: string;
            last_name: string;
            email: string;
            username: string;
            googleId: string;
            roles: ("user" | "admin")[];
            organization: components["schemas"]["Organization"];
            organizationId: number;
            createdApps: components["schemas"]["App"][];
            memberships: components["schemas"]["UserOrganization"][];
            /** Format: date-time */
            deletedAt?: string;
        };
        SwitchOrgDto: {
            organizationId: number;
        };
        CreateInvitationDto: {
            invitedEmail: string;
            /** @enum {string} */
            desired_role: "user" | "admin";
        };
        CreateApiKeyDto: {
            name: string;
            organizationId: number;
            appId?: number;
            /**
             * @default [
             *       "publish",
             *       "subscribe"
             *     ]
             */
            scopes: ("publish" | "subscribe" | "events:read" | "traces:read" | "apps:manage" | "channels:manage" | "webhooks:manage")[];
        };
        ApiKeyResponseDto: {
            id: number;
            name: string;
            prefix: string;
            /** @description Raw API key, only returned at creation time */
            key: string;
            scopes: ("publish" | "subscribe" | "events:read" | "traces:read" | "apps:manage" | "channels:manage" | "webhooks:manage")[];
            /** Format: date-time */
            createdAt: string;
        };
        ApiKey: {
            id: number;
            name: string;
            prefix: string;
            hashedKey: string;
            app: components["schemas"]["App"];
            appId: number;
            organization: components["schemas"]["Organization"];
            organizationId: number;
            scopes: string[];
            createdBy: components["schemas"]["User"];
            createdById: number;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
        };
        CreateAppDto: {
            name: string;
        };
        createChannelDto: {
            name: string;
            appId: number;
        };
        CreateEventDto: {
            identifier: string;
            payload: Record<string, never>;
            channel_id: number;
            agentId?: string;
            traceId?: string;
            spanId?: string;
            parentEventId?: number;
            /**
             * @default custom
             * @enum {string}
             */
            eventType: "agent.start" | "agent.end" | "agent.message" | "agent.tool_call.start" | "agent.tool_call.end" | "agent.error" | "agent.handoff" | "agent.llm.token" | "agent.log" | "app.log" | "app.span" | "custom";
            metadata?: Record<string, never>;
        };
        CreateWebhookEndpointDto: {
            url: string;
            channelId: number;
            secret?: string;
            /** @description Event types to filter (null = all) */
            eventTypes?: string[];
            description?: string;
        };
        WebhookEndpoint: {
            id: number;
            url: string;
            secret: string;
            channel: components["schemas"]["Channel"];
            channelId: number;
            eventTypes: string[];
            active: boolean;
            description: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WebhookDelivery: {
            id: number;
            endpoint: components["schemas"]["WebhookEndpoint"];
            endpointId: number;
            eventId: number;
            /** @enum {string} */
            status: "pending" | "success" | "failed" | "retrying";
            attempts: number;
            statusCode: number;
            responseBody: string;
            error: string;
            /** Format: date-time */
            nextRetryAt: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_setupOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupOrgDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_getMyOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOrganization"][];
                };
            };
        };
    };
    UserController_switchActiveOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrgDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_getAllOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
        };
    };
    OrganizationController_createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    OrganizationController_deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_editOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    OrganizationController_deleteInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                invitationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApiKeyController_listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
        };
    };
    ApiKeyController_createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponseDto"];
                };
            };
        };
    };
    ApiKeyController_revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppsController_getAllApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"][];
                };
            };
        };
    };
    AppsController_createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
        };
    };
    AppsController_getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
        };
    };
    AppsController_deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppsController_editApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChannelController_subscribeToChannel: {
        parameters: {
            query: {
                agentId: string;
                eventType: string;
                traceId: string;
            };
            header?: never;
            path: {
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChannelController_subscribeToEvent: {
        parameters: {
            query: {
                agentId: string;
                eventType: string;
                traceId: string;
            };
            header?: never;
            path: {
                channelId: number;
                eventIdentifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChannelController_getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
        };
    };
    ChannelController_updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChannelController_deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChannelController_createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["createChannelDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
        };
    };
    EventController_createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    EventController_listEvents: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Lucene query filtering JSONB payload. Examples: severityNumber:>=17, body:/timeout/, resource.service.name:api */
                q?: string;
                /** @description ISO timestamp — earliest createdAt to include */
                since?: string;
                /** @description ISO timestamp — latest createdAt to include */
                until?: string;
                /** @description Convenience filter on eventType prefix */
                source?: "agent" | "app" | "all";
            };
            header?: never;
            path: {
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Event"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    EventsSearchController_search: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Lucene query filtering JSONB payload. Examples: severityNumber:>=17, body:/timeout/, resource.service.name:api */
                q?: string;
                /** @description ISO timestamp — earliest createdAt to include */
                since?: string;
                /** @description ISO timestamp — latest createdAt to include */
                until?: string;
                /** @description Convenience filter on eventType prefix */
                source?: "agent" | "app" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Event"][];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    WebhookController_createEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookEndpointDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
        };
    };
    WebhookController_listEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"][];
                };
            };
        };
    };
    WebhookController_deleteEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WebhookController_getDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDelivery"][];
                };
            };
        };
    };
    WebhookController_ingestWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-webhook-signature": string;
            };
            path: {
                endpointId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TraceController_listTraces: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of trace summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            traceId: string;
                            eventCount: number;
                            agents: string[];
                            eventTypes: string[];
                            /** Format: date-time */
                            startTime: string;
                            /** Format: date-time */
                            endTime: string;
                            duration: number;
                            errorCount: number;
                            toolCallCount: number;
                            handoffCount: number;
                        }[];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    TraceController_getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated dashboard stats for the caller organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalEvents: number;
                        eventsToday: number;
                        totalTraces: number;
                        tracesToday: number;
                        errorCount: number;
                        errorRate: number;
                        avgTraceDuration: number;
                        eventsByHour: {
                            /** Format: date-time */
                            hour?: string;
                            count?: number;
                        }[];
                    };
                };
            };
        };
    };
    TraceController_getTraceEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All events belonging to a trace, ordered by createdAt ASC */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    TraceController_getTraceSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated summary for a single trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        traceId: string;
                        eventCount: number;
                        agents: string[];
                        eventTypes: string[];
                        /** Format: date-time */
                        startTime: string;
                        /** Format: date-time */
                        endTime: string;
                        duration: number;
                        errorCount: number;
                        toolCallCount: number;
                        handoffCount: number;
                    };
                };
            };
        };
    };
    AuditLogController_listAuditLogs: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                action?: string;
                resourceType?: string;
                actorId?: number;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of audit log entries for the caller organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: number;
                            organizationId?: number;
                            actorId?: number | null;
                            action: string;
                            resourceType: string;
                            resourceId: string;
                            metadata?: {
                                [key: string]: unknown;
                            } | null;
                            ipAddress?: string | null;
                            actor?: {
                                id?: number;
                                first_name?: string;
                                last_name?: string;
                                email?: string;
                                username?: string;
                            } | null;
                            /** Format: date-time */
                            createdAt: string;
                        }[];
                        meta: {
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    OtlpController_ingestLogs: {
        parameters: {
            query?: never;
            header: {
                "x-axonpush-channel": string;
                /** @description Numeric ID of the channel that should receive these events */
                "X-Axonpush-Channel": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty object on full success, or `{partialSuccess: {rejectedLogRecords, errorMessage}}` if some records failed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        partialSuccess?: {
                            rejectedLogRecords?: number;
                            errorMessage?: string;
                        };
                    };
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    OtlpController_ingestTraces: {
        parameters: {
            query?: never;
            header: {
                "x-axonpush-channel": string;
                /** @description Numeric ID of the channel that should receive these events */
                "X-Axonpush-Channel": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty object on full success, or `{partialSuccess: {rejectedSpans, errorMessage}}` if some spans failed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        partialSuccess?: {
                            rejectedSpans?: number;
                            errorMessage?: string;
                        };
                    };
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
