/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_googleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_setupOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/iot-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IotCredentialsController_getCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_updateMe"];
        trace?: never;
    };
    "/users/me/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getMyOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/active-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UserController_switchActiveOrg"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UserController_updateUser"];
        post?: never;
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationController_getAllOrganizations"];
        put?: never;
        post: operations["OrganizationController_createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizationController_getOrganization"];
        put?: never;
        post?: never;
        delete: operations["OrganizationController_deleteOrganization"];
        options?: never;
        head?: never;
        patch: operations["OrganizationController_editOrganization"];
        trace?: never;
    };
    "/organizations/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationController_createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganizationController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrganizationController_transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrganizationController_deleteInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-flags/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeatureFlagsController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EnvironmentController_list"];
        put?: never;
        post: operations["EnvironmentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["EnvironmentController_remove"];
        options?: never;
        head?: never;
        patch: operations["EnvironmentController_update"];
        trace?: never;
    };
    "/environments/{id}/promote-to-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EnvironmentController_promote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApiKeyController_listApiKeys"];
        put?: never;
        post: operations["ApiKeyController_createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ApiKeyController_revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicIngestTokenController_list"];
        put?: never;
        post: operations["PublicIngestTokenController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PublicIngestTokenController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChannelController_getChannel"];
        put: operations["ChannelController_updateChannel"];
        post?: never;
        delete: operations["ChannelController_deleteChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChannelController_createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{channelId}/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventController_listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsSearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppsController_getAllApps"];
        put?: never;
        post: operations["AppsController_createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppsController_getApp"];
        put?: never;
        post?: never;
        delete: operations["AppsController_deleteApp"];
        options?: never;
        head?: never;
        patch: operations["AppsController_editApp"];
        trace?: never;
    };
    "/webhooks/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebhookController_createEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/endpoints/channel/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WebhookController_listEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WebhookController_deleteEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/deliveries/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WebhookController_getDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/ingest/{endpointId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebhookController_ingestWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{traceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getTraceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{traceId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TraceController_getTraceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditLogController_listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OTLP/HTTP logs ingest (protobuf or JSON) */
        post: operations["OtlpController_ingestLogs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OTLP/HTTP traces ingest (protobuf or JSON) */
        post: operations["OtlpController_ingestTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReleaseController_list"];
        put?: never;
        post: operations["ReleaseController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{version}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReleaseController_uploadArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{projectId}/envelope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sentry-compatible envelope ingest */
        post: operations["SentryController_ingestEnvelope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{projectId}/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SentryController_ingestStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{projectId}/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SentryController_ingestSecurity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{projectId}/minidump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SentryController_ingestMinidump"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sso/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_getConnections"];
        put?: never;
        post: operations["SsoController_createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sso/connections/{clientID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SsoController_deleteConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sso/enforcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["SsoController_toggleEnforcement"];
        trace?: never;
    };
    "/auth/sso/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoController_authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SsoController_callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/acs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SsoController_samlAcs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrganizationDto: {
            name: string;
            slug: string;
            description?: string;
        };
        UserCreateDto: {
            email: string;
            username: string;
            first_name: string;
            last_name: string;
            password: string;
            /** @enum {string} */
            action: "create" | "join";
            orgCreateProps?: components["schemas"]["CreateOrganizationDto"];
            invitationCode?: string;
        };
        UserResponseDto: {
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            username: string;
            googleId: string | null;
            roles: ("user" | "admin" | "owner")[];
            organizationId: string | null;
            deletedAt?: string | null;
        };
        SignInDto: {
            email: string;
            password: string;
        };
        AuthTokensResponseDto: {
            access_token: string;
            refresh_token: string;
        };
        GoogleAuthDto: {
            code?: string;
            idToken?: string;
        };
        GoogleAuthResponseDto: {
            access_token: string;
            refresh_token: string;
            needsOrg?: boolean;
        };
        SetupOrgDto: {
            /** @enum {string} */
            action: "create" | "join";
            orgCreateProps?: components["schemas"]["CreateOrganizationDto"];
            invitationCode?: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        IotCredentialsResponseDto: {
            endpoint: string;
            presignedWssUrl: string;
            expiresAt: string;
            topicPrefix: string;
            clientId: string;
            region: string;
        };
        UpdateProfileDto: {
            first_name?: string;
            last_name?: string;
        };
        InvitationResponseDto: {
            id: string;
            invitationId: string;
            orgId: string;
            invitedEmail: string;
            role: string;
            inviteRole?: string;
            code?: string;
            status: string;
            expiresAt?: string;
            acceptedAt?: string;
            createdAt: string;
            updatedAt?: string;
        };
        EnvironmentResponseDto: {
            id: string;
            environmentId: string;
            orgId: string;
            name: string;
            slug: string;
            color?: string;
            isDefault?: boolean;
            isProduction?: boolean;
            isEphemeral?: boolean;
            expiresAt?: string;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
        };
        OrganizationResponseDto: {
            id: string;
            orgId: string;
            name: string;
            slug: string;
            description?: string;
            plan: string;
            ssoEnforced: boolean;
            eventsQuotaUsedCurrent: number;
            eventsQuotaMonthly?: number;
            retentionDays?: number;
            seatLimit?: number;
            lemonsqueezySubscriptionId?: string;
            lemonsqueezyCustomerId?: string;
            ssoConnectionId?: string;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
            invitations?: components["schemas"]["InvitationResponseDto"][];
            environments?: components["schemas"]["EnvironmentResponseDto"][];
        };
        UserOrganizationWithOrgResponseDto: {
            userId: string;
            orgId: string;
            role: string;
            joinedAt: string;
            deletedAt?: string;
            organization?: components["schemas"]["OrganizationResponseDto"] | null;
        };
        SwitchOrgDto: {
            organizationId: string;
        };
        SwitchActiveOrgResponseDto: {
            access_token: string;
            refresh_token: string;
            user?: components["schemas"]["UserResponseDto"];
        };
        MessageResponseDto: {
            message: string;
        };
        OrganizationCreateResponseDto: {
            id: string;
            orgId: string;
            name: string;
            slug: string;
            description?: string;
            plan: string;
            ssoEnforced: boolean;
            eventsQuotaUsedCurrent: number;
            eventsQuotaMonthly?: number;
            retentionDays?: number;
            seatLimit?: number;
            lemonsqueezySubscriptionId?: string;
            lemonsqueezyCustomerId?: string;
            ssoConnectionId?: string;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
            invitations?: components["schemas"]["InvitationResponseDto"][];
            environments?: components["schemas"]["EnvironmentResponseDto"][];
            access_token: string;
            refresh_token: string;
        };
        OkResponseDto: {
            ok: boolean;
        };
        CreateInvitationDto: {
            invitedEmail: string;
            /** @enum {string} */
            desired_role: "user" | "admin";
        };
        SuccessResponseDto: {
            success: boolean;
        };
        TransferOwnershipDto: {
            userId: string;
        };
        FeatureFlagsResponseDto: {
            billing: boolean;
            environments: boolean;
            sentryIngest: boolean;
            asyncIngest: boolean;
        };
        CreateEnvironmentDto: {
            name: string;
            slug?: string;
            color?: string;
            isProduction?: boolean;
            isDefault?: boolean;
            cloneFromEnvId?: string;
        };
        UpdateEnvironmentDto: {
            name?: string;
            color?: string;
            requireConfirmationForDestructive?: boolean;
        };
        CreateApiKeyDto: {
            name: string;
            organizationId: string;
            appId?: string;
            /** @description Environment this key is bound to. All events published with this key will be tagged with this environment (unless allowEnvironmentOverride=true and the request specifies a different one). */
            environmentId?: string;
            /**
             * @description When true, the caller may override the env via X-Axonpush-Environment header or the event.environment field. Defaults to false for safety.
             * @default false
             */
            allowEnvironmentOverride: boolean;
            /**
             * @default [
             *       "publish",
             *       "subscribe"
             *     ]
             */
            scopes: ("publish" | "subscribe" | "events:read" | "traces:read" | "apps:manage" | "channels:manage" | "webhooks:manage")[];
        };
        ApiKeyCreateResponseDto: {
            id: string;
            apiKeyId: string;
            orgId: string;
            appId?: string;
            environmentId?: string;
            name: string;
            scopes: ("publish" | "subscribe" | "events:read" | "traces:read" | "apps:manage" | "channels:manage" | "webhooks:manage")[];
            allowEnvironmentOverride: boolean;
            prefix?: string;
            lastUsedAt?: string;
            createdAt: string;
            updatedAt?: string;
            revokedAt?: string;
            /** @description Raw API key, only returned at creation time */
            key: string;
        };
        ApiKeyResponseDto: {
            id: string;
            apiKeyId: string;
            orgId: string;
            appId?: string;
            environmentId?: string;
            name: string;
            scopes: ("publish" | "subscribe" | "events:read" | "traces:read" | "apps:manage" | "channels:manage" | "webhooks:manage")[];
            allowEnvironmentOverride: boolean;
            prefix?: string;
            lastUsedAt?: string;
            createdAt: string;
            updatedAt?: string;
            revokedAt?: string;
        };
        CreatePublicTokenDto: {
            name: string;
            channelId: string;
            environmentId: string;
        };
        PublicIngestTokenCreateResponseDto: {
            id: string;
            tokenId: string;
            orgId: string;
            appId?: string;
            channelId?: string;
            environmentId?: string;
            name: string;
            scopes?: string[];
            prefix?: string;
            lastUsedAt?: string;
            createdAt: string;
            revokedAt?: string;
            /** @description Raw token, only returned at creation time */
            token: string;
        };
        PublicIngestTokenResponseDto: {
            id: string;
            tokenId: string;
            orgId: string;
            appId?: string;
            channelId?: string;
            environmentId?: string;
            name: string;
            scopes?: string[];
            prefix?: string;
            lastUsedAt?: string;
            createdAt: string;
            revokedAt?: string;
        };
        ChannelResponseDto: {
            id: string;
            channelId: string;
            orgId: string;
            appId: string;
            name: string;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
            app?: components["schemas"]["AppResponseDto"];
        };
        AppResponseDto: {
            id: string;
            appId: string;
            orgId: string;
            name: string;
            creatorUserId?: string;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
            channels?: components["schemas"]["ChannelResponseDto"][];
        };
        createChannelDto: {
            name: string;
            appId: string;
        };
        CreateEventDto: {
            identifier: string;
            payload: Record<string, never>;
            channel_id: string;
            agentId?: string;
            traceId?: string;
            spanId?: string;
            parentEventId?: string;
            /**
             * @default custom
             * @enum {string}
             */
            eventType: "agent.start" | "agent.end" | "agent.message" | "agent.tool_call.start" | "agent.tool_call.end" | "agent.error" | "agent.handoff" | "agent.llm.token" | "agent.log" | "app.log" | "app.span" | "custom";
            metadata?: Record<string, never>;
            /** @description Environment slug override. Only honored when the API key has allowEnvironmentOverride=true. */
            environment?: string;
            /**
             * @description When true, wait for the event to be persisted to the DB before returning. Use only for audit-critical calls — the default async path returns in under a millisecond.
             * @default false
             */
            sync: boolean;
        };
        EventIngestResponseDto: {
            eventId: string;
            identifier: string;
            dedupKey: string;
            createdAt: string;
            queued: boolean;
            duplicate?: boolean;
            environmentId?: string | null;
        };
        EventResponseDto: {
            id: string;
            eventId: string;
            orgId: string;
            appId: string;
            channelId: string;
            environmentId?: string;
            eventType: string;
            agentId?: string;
            traceId?: string;
            spanId?: string;
            parentEventId?: string;
            identifier?: string;
            payload?: {
                [key: string]: unknown;
            };
            metadata?: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt?: string;
            ttl?: number;
        };
        EventListMetaDto: {
            hasMore: boolean;
            cursor?: string | null;
        };
        EventListResponseDto: {
            data: components["schemas"]["EventResponseDto"][];
            meta: components["schemas"]["EventListMetaDto"];
        };
        CreateAppDto: {
            name: string;
        };
        CreateWebhookEndpointDto: {
            url: string;
            channelId: string;
            secret?: string;
            /** @description Event types to filter (null = all) */
            eventTypes?: string[];
            description?: string;
        };
        WebhookEndpointCreateResponseDto: {
            id: string;
            endpointId: string;
            orgId?: string;
            channelId: string;
            url: string;
            eventTypes?: string[];
            signingSecretPrefix?: string;
            hasSecret?: boolean;
            description?: string;
            isActive: boolean;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
            /** @description Raw signing secret, only returned at creation time */
            rawSecret?: string;
            /** @description Prefix of the signing secret */
            secretPrefix?: string | null;
        };
        WebhookEndpointResponseDto: {
            id: string;
            endpointId: string;
            orgId?: string;
            channelId: string;
            url: string;
            eventTypes?: string[];
            signingSecretPrefix?: string;
            hasSecret?: boolean;
            description?: string;
            isActive: boolean;
            createdAt: string;
            updatedAt?: string;
            deletedAt?: string;
        };
        WebhookDeliveryResponseDto: {
            id: string;
            deliveryId: string;
            endpointId: string;
            eventId: string;
            /** @enum {string} */
            status: "pending" | "success" | "failed" | "retrying";
            statusCode?: number;
            responseBody?: string;
            attempts: number;
            lastAttemptAt?: string;
            nextAttemptAt?: string;
            error?: string;
            createdAt: string;
        };
        WebhookIngestResponseDto: {
            status: string;
            eventId: string;
        };
        AuditLogActorDto: {
            id: string;
            first_name?: string;
            last_name?: string;
            email?: string;
            username?: string;
        };
        AuditLogResponseDto: {
            id: string;
            auditId: string;
            organizationId?: string;
            orgId?: string;
            actorId?: string | null;
            action: string;
            resourceType: string;
            resourceId?: string;
            metadata?: {
                [key: string]: unknown;
            } | null;
            ipAddress?: string | null;
            actor?: components["schemas"]["AuditLogActorDto"] | null;
            createdAt: string;
        };
        AuditLogListMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        AuditLogListResponseDto: {
            data: components["schemas"]["AuditLogResponseDto"][];
            meta: components["schemas"]["AuditLogListMetaDto"];
        };
        HealthResponseDto: {
            status: string;
            timestamp: string;
            flags: {
                [key: string]: unknown;
            };
        };
        CreateReleaseDto: {
            version: string;
            projects?: string[];
            dateReleased?: string;
        };
        ReleaseResponseDto: {
            orgId: string;
            version: string;
            projects?: string;
            dateCreated: string;
            dateReleased?: string;
            firstEventAt?: string;
            lastEventAt?: string;
        };
        ReleaseArtifactResponseDto: {
            orgId: string;
            version: string;
            artifactId: string;
            name: string;
            contentType?: string;
            sizeBytes: number;
            storagePath: string;
            sha256?: string;
            createdAt: string;
        };
        SsoConnectionResponseDto: {
            clientID: string;
            tenant?: string;
            product?: string;
            defaultRedirectUrl?: string;
            redirectUrl?: string[];
        };
        ToggleEnforcementDto: {
            enforced: boolean;
        };
        SsoEnforcementResponseDto: {
            ok: boolean;
            enforced: boolean;
        };
        SsoAuthorizeResponseDto: {
            redirect_url: string;
        };
        SsoCallbackDto: {
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    AuthController_setupOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupOrgDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IotCredentialsController_getCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IotCredentialsResponseDto"];
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_getMyOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOrganizationWithOrgResponseDto"][];
                };
            };
        };
    };
    UserController_switchActiveOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrgDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchActiveOrgResponseDto"];
                };
            };
        };
    };
    UserController_getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    OrganizationController_getAllOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"][];
                };
            };
        };
    };
    OrganizationController_createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationCreateResponseDto"];
                };
            };
        };
    };
    OrganizationController_getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    OrganizationController_deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    OrganizationController_editOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    OrganizationController_createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponseDto"];
                };
            };
        };
    };
    OrganizationController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    OrganizationController_transferOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_deleteInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    FeatureFlagsController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagsResponseDto"];
                };
            };
        };
    };
    EnvironmentController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponseDto"][];
                };
            };
        };
    };
    EnvironmentController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponseDto"];
                };
            };
        };
    };
    EnvironmentController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    EnvironmentController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnvironmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponseDto"];
                };
            };
        };
    };
    EnvironmentController_promote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ApiKeyController_listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponseDto"][];
                };
            };
        };
    };
    ApiKeyController_createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponseDto"];
                };
            };
        };
    };
    ApiKeyController_revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    PublicIngestTokenController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicIngestTokenResponseDto"][];
                };
            };
        };
    };
    PublicIngestTokenController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePublicTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicIngestTokenCreateResponseDto"];
                };
            };
        };
    };
    PublicIngestTokenController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    ChannelController_getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponseDto"];
                };
            };
        };
    };
    ChannelController_updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    ChannelController_deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    ChannelController_createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["createChannelDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelResponseDto"];
                };
            };
        };
    };
    EventController_createEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Stripe-style client-supplied idempotency key (1–255 ASCII-printable chars). Cached response replay for retried requests. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventIngestResponseDto"];
                };
            };
        };
    };
    EventController_listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponseDto"];
                };
            };
        };
    };
    EventsSearchController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponseDto"];
                };
            };
        };
    };
    AppsController_getAllApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponseDto"][];
                };
            };
        };
    };
    AppsController_createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponseDto"];
                };
            };
        };
    };
    AppsController_getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponseDto"];
                };
            };
        };
    };
    AppsController_deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    AppsController_editApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    WebhookController_createEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookEndpointDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointCreateResponseDto"];
                };
            };
        };
    };
    WebhookController_listEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointResponseDto"][];
                };
            };
        };
    };
    WebhookController_deleteEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WebhookController_getDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDeliveryResponseDto"][];
                };
            };
        };
    };
    WebhookController_ingestWebhook: {
        parameters: {
            query?: never;
            header: {
                "x-webhook-signature": string;
            };
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookIngestResponseDto"];
                };
            };
        };
    };
    TraceController_listTraces: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                appId?: string;
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of trace summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            traceId: string;
                            eventCount: number;
                            agents: string[];
                            eventTypes: string[];
                            /** Format: date-time */
                            startTime: string;
                            /** Format: date-time */
                            endTime: string;
                            duration: number;
                            errorCount: number;
                            toolCallCount: number;
                            handoffCount: number;
                        }[];
                        meta: {
                            page: number;
                            limit: number;
                            hasMore: boolean;
                        };
                    };
                };
            };
        };
    };
    TraceController_getDashboardStats: {
        parameters: {
            query?: {
                appId?: string;
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated dashboard stats for the caller organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalEvents: number;
                        eventsToday: number;
                        totalTraces: number;
                        tracesToday: number;
                        errorCount: number;
                        errorRate: number;
                        avgTraceDuration: number;
                        eventsByHour: {
                            /** Format: date-time */
                            hour?: string;
                            count?: number;
                        }[];
                    };
                };
            };
        };
    };
    TraceController_getTraceEvents: {
        parameters: {
            query?: {
                appId?: string;
                environment?: string;
            };
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All events belonging to a trace, ordered by createdAt ASC */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"][];
                };
            };
        };
    };
    TraceController_getTraceSummary: {
        parameters: {
            query?: {
                appId?: string;
                environment?: string;
            };
            header?: never;
            path: {
                traceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated summary for a single trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        traceId: string;
                        eventCount: number;
                        agents: string[];
                        eventTypes: string[];
                        /** Format: date-time */
                        startTime: string;
                        /** Format: date-time */
                        endTime: string;
                        duration: number;
                        errorCount: number;
                        toolCallCount: number;
                        handoffCount: number;
                    };
                };
            };
        };
    };
    AuditLogController_listAuditLogs: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                action?: string;
                resourceType?: string;
                actorId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of audit log entries for the caller organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponseDto"];
                };
            };
        };
    };
    OtlpController_ingestLogs: {
        parameters: {
            query?: never;
            header: {
                "x-axonpush-channel": string;
                "x-axonpush-environment": string;
                "Idempotency-Key"?: string;
                "X-Axonpush-Environment"?: string;
                "X-Axonpush-Channel"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    OtlpController_ingestTraces: {
        parameters: {
            query?: never;
            header: {
                "x-axonpush-channel": string;
                "x-axonpush-environment": string;
                "Idempotency-Key"?: string;
                "X-Axonpush-Environment"?: string;
                "X-Axonpush-Channel"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    ReleaseController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseResponseDto"][];
                };
            };
        };
    };
    ReleaseController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseResponseDto"];
                };
            };
        };
    };
    ReleaseController_uploadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseArtifactResponseDto"];
                };
            };
        };
    };
    SentryController_ingestEnvelope: {
        parameters: {
            query?: never;
            header: {
                "content-encoding": string;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SentryController_ingestStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SentryController_ingestSecurity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SentryController_ingestMinidump: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoController_getConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoConnectionResponseDto"][];
                };
            };
        };
    };
    SsoController_createConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoConnectionResponseDto"];
                };
            };
        };
    };
    SsoController_deleteConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponseDto"];
                };
            };
        };
    };
    SsoController_toggleEnforcement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleEnforcementDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoEnforcementResponseDto"];
                };
            };
        };
    };
    SsoController_authorize: {
        parameters: {
            query?: {
                email?: string;
                org_slug?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoAuthorizeResponseDto"];
                };
            };
        };
    };
    SsoController_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoCallbackDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponseDto"];
                };
            };
        };
    };
    SsoController_samlAcs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
